### ISSUE TITLE
How to Mange Inbounds clients

### ISSUE THREAD

**Issue by mramirghafari** [alirezax5/xuiapi#1]
Hi. I want to add many clients for one inbound with one port via API! but I dont know how to do it. anybody can help me?

**Comment by netparadis** [comment]
سلام.  clientStats که در خروجی اون پورت هست رو دریافت می کنید و بعد یه کلاینت جدید به ارایه اون اضافه و بعد دوباره update رو میفرستید

سورس کامل به همراه ربات تلگرام php ساخت اکانت رو اینجا میتونید ببینید :
https://netparadis.com/telegram-account-shop-bot-php/

**Comment by alirezax5** [comment]
> Hi. I want to add many clients for one inbound with one port via API! but I dont know how to do it. anybody can help me?

سلام آقا حسن توضیح دادن و خودشون ربات تلگرامش نوشتن اگه خودت حوصله و‌وقت کد زدن نداری هزینه کنی بهتره😄

**Comment by alirezax5** [comment]
> سلام. clientStats که در خروجی اون پورت هست رو دریافت می کنید و بعد یه کلاینت جدید به ارایه اون اضافه و بعد دوباره update رو میفرستید
> 
> سورس کامل به همراه ربات تلگرام php ساخت اکانت رو اینجا میتونید ببینید : https://netparadis.com/telegram-account-shop-bot-php/


سلام
فقط با x-ui حسین مچه یا بقیه پنل ها هم اوک کردین؟ و قابلیت اضافه کردن چندتا سرور هم گذاشتید؟

**Comment by mramirghafari** [comment]
> 

خیلی خیلی عالیه فقط اینکه با کدوم پنل ها اوکی هست؟
ما پنل حسین اسدی استفاده میکنیم! یعنی روی یه پورت کلی کلاینت داریم و این مشکل اصلی من بوده ایا تو این ربات این مشکل برطرف شده؟

**Comment by netparadis** [comment]
> > سلام. clientStats که در خروجی اون پورت هست رو دریافت می کنید و بعد یه کلاینت جدید به ارایه اون اضافه و بعد دوباره update رو میفرستید
> > سورس کامل به همراه ربات تلگرام php ساخت اکانت رو اینجا میتونید ببینید : https://netparadis.com/telegram-account-shop-bot-php/
> 
> سلام فقط با x-ui حسین مچه یا بقیه پنل ها هم اوک کردین؟ و قابلیت اضافه کردن چندتا سرور هم گذاشتید؟

بله با بقیه پنل های xui و پلن اسدی سازگاره و قابلیت اضافه کردن بی نهایت سرور هم داره

**Comment by netparadis** [comment]
> > 
> 
> خیلی خیلی عالیه فقط اینکه با کدوم پنل ها اوکی هست؟ ما پنل حسین اسدی استفاده میکنیم! یعنی روی یه پورت کلی کلاینت داریم و این مشکل اصلی من بوده ایا تو این ربات این مشکل برطرف شده؟

بله شما میتونید به دو روش پلن تعریف کنید یکی اینکه برای هر کاربر پورت اختصاصی بسازه یا اینکه روی یه پورت بی نهایت کلاینت بسازید.

می تونید محدودیت تعداد هم بزارید به اینصورت اینکه روی یه پورت چندتا بسازه و دیگه اجازه نده یا روی یه سرور چندتا کانکشن بسازه و بعد اجازه نده
