### ISSUE TITLE
بهم ریختن پنل بعد از افزودن کلاینت

### ISSUE THREAD

**Issue by mostafa9112** [alirezax5/xuiapi#10]
سلام بعد از اجرای دستور زیر پنل بهم میریزه
$xui->addnewClient('1','fd7d9f1f-2b0a-4494-bee9-f06248e97272','test@test.ir','','5','5','5')
پنل ثنایی نصب دارم 
بعد از اجرای دستور پیغام زیر میاد و پنل بهم میریزه

{
  "success": true,
  "msg": "修改成功",
  "obj": {
    "id": 1,
    "up": 0,
    "down": 0,
    "total": 0,
    "remark": "",
    "enable": false,
    "expiryTime": 0,
    "clientStats": null,
    "listen": "",
    "port": 0,
    "protocol": "",
    "settings": "{\"clients\":[{\"id\":\"fd7d9f1f-2b0a-4494-bee9-f06248e97272\",\"email\":\"test@test.ir\",\"flow\":\"\",\"totalGB\":5368709120,\"expiryTime\":\"5\",\"limitIp\":\"5\",\"fingerprint\":\"chrome\"}]}",
    "streamSettings": "null",
    "tag": "",
    "sniffing": "{\"enabled\":true,\"destOverride\":[\"http\",\"tls\"]}"
  }
}

**Comment by alirezax5** [comment]
> سلام بعد از اجرای دستور زیر پنل بهم میریزه $xui->addnewClient('1','fd7d9f1f-2b0a-4494-bee9-f06248e97272','[test@test.ir](mailto:test@test.ir)','','5','5','5') پنل ثنایی نصب دارم بعد از اجرای دستور پیغام زیر میاد و پنل بهم میریزه
> 
> { "success": true, "msg": "修改成功", "obj": { "id": 1, "up": 0, "down": 0, "total": 0, "remark": "", "enable": false, "expiryTime": 0, "clientStats": null, "listen": "", "port": 0, "protocol": "", "settings": "{"clients":[{"id":"fd7d9f1f-2b0a-4494-bee9-f06248e97272","email":"[test@test.ir](mailto:test@test.ir)","flow":"","totalGB":5368709120,"expiryTime":"5","limitIp":"5","fingerprint":"chrome"}]}", "streamSettings": "null", "tag": "", "sniffing": "{"enabled":true,"destOverride":["http","tls"]}" } }

اون موقع با ثنایی تست کرد مشکلی نداشت , xray خاموش میشه ؟ و خطاش چیه

**Comment by alirezax5** [comment]
> سلام بعد از اجرای دستور زیر پنل بهم میریزه $xui->addnewClient('1','fd7d9f1f-2b0a-4494-bee9-f06248e97272','[test@test.ir](mailto:test@test.ir)','','5','5','5') پنل ثنایی نصب دارم بعد از اجرای دستور پیغام زیر میاد و پنل بهم میریزه
> 
> { "success": true, "msg": "修改成功", "obj": { "id": 1, "up": 0, "down": 0, "total": 0, "remark": "", "enable": false, "expiryTime": 0, "clientStats": null, "listen": "", "port": 0, "protocol": "", "settings": "{"clients":[{"id":"fd7d9f1f-2b0a-4494-bee9-f06248e97272","email":"[test@test.ir](mailto:test@test.ir)","flow":"","totalGB":5368709120,"expiryTime":"5","limitIp":"5","fingerprint":"chrome"}]}", "streamSettings": "null", "tag": "", "sniffing": "{"enabled":true,"destOverride":["http","tls"]}" } }

ایدی inbound که دادی توی پنل هستش ؟

**Comment by alirezax5** [comment]
> سلام بعد از اجرای دستور زیر پنل بهم میریزه $xui->addnewClient('1','fd7d9f1f-2b0a-4494-bee9-f06248e97272','[test@test.ir](mailto:test@test.ir)','','5','5','5') پنل ثنایی نصب دارم بعد از اجرای دستور پیغام زیر میاد و پنل بهم میریزه
> 
> { "success": true, "msg": "修改成功", "obj": { "id": 1, "up": 0, "down": 0, "total": 0, "remark": "", "enable": false, "expiryTime": 0, "clientStats": null, "listen": "", "port": 0, "protocol": "", "settings": "{"clients":[{"id":"fd7d9f1f-2b0a-4494-bee9-f06248e97272","email":"[test@test.ir](mailto:test@test.ir)","flow":"","totalGB":5368709120,"expiryTime":"5","limitIp":"5","fingerprint":"chrome"}]}", "streamSettings": "null", "tag": "", "sniffing": "{"enabled":true,"destOverride":["http","tls"]}" } }

همین الان تست کردم اوک بود
