### ISSUE TITLE
ایراد در اجرا

### ISSUE THREAD

**Issue by elegance666** [alirezax5/xuiapi#13]
سلام، 
بعد از نصب و اجرا صفحه سفید میاد بدون هیچ خروجی یا لاگی...

**Comment by alirezax5** [comment]
> سلام، بعد از نصب و اجرا صفحه سفید میاد بدون هیچ خروجی یا لاگی...

احتمالا از لاگینه به متدش ورودی true اضافه کن و چک کن اطلاعات پنل درست داده باشی اگه پچ داره پچشم بزار
مثلا :
```php
require __DIR__ . '/vendor/autoload.php';
$xui = new \alirezax5\XuiApi\Panel\Vaxilu('192.168.1.1:8080', 'YOU_PANEL_USERNAME', 'YOU_PANEL_PASSWORD');
#Set Up Cookie
$xui->setCookie(__DIR__.'/Cookie.txt');
$xui->login(true);
```
اگه path گذاشتی :
```php
$xui = new \alirezax5\XuiApi\Panel\Vaxilu('192.168.1.1:8080/path', 'YOU_PANEL_USERNAME', 'YOU_PANEL_PASSWORD');
```
و اگه توی سی پنل کد رو داری اجرا میکنی حتما روی پروت های شناخته شده بزار بقیش باید توی فایروال باز کنی
و اگه توی سروره حتما به فایل کوکی دسترسی بده

**Comment by elegance666** [comment]
راه افتاد، دست درد نکنه واقعا، همون true کم بود
