### ISSUE TITLE
مشکل محاسبه ترافیک

### ISSUE THREAD

**Issue by sajjad5221** [alirezax5/xuiapi#14]
سلام وقت بخیر. وقتی کلاینت با استفاده از این API و مدل سنائی اضافه میکنم یه مشکلی به وجود میاد. رفتم بررسی کردم دیدم وقتی از داخل پنل یوزر ساخته بشه داخل جدول clients_traffic هم اون یوزر ساخته میشه و اونجوری محاسبه حجم هم انجام میشه. ولی وقتی با استفاده از این API این کار میکنم یوزر داخل جدول clients_traffic ساخته نمیشه و خب محاسبه حجم هم انجام نمیشه. البته حتی وقتی دستی هم رفتم یوزر تو این جدول اضافه کردم باز هم محاسبه حجم انجام نشد!
 نمیدونم که مشکل از API هست یا خود پنل ولی احتمال بالا مشکل از API هست.

**Comment by alirezax5** [comment]
> سلام وقت بخیر. وقتی کلاینت با استفاده از این API و مدل سنائی اضافه میکنم یه مشکلی به وجود میاد. رفتم بررسی کردم دیدم وقتی از داخل پنل یوزر ساخته بشه داخل جدول clients_traffic هم اون یوزر ساخته میشه و اونجوری محاسبه حجم هم انجام میشه. ولی وقتی با استفاده از این API این کار میکنم یوزر داخل جدول clients_traffic ساخته نمیشه و خب محاسبه حجم هم انجام نمیشه. البته حتی وقتی دستی هم رفتم یوزر تو این جدول اضافه کردم باز هم محاسبه حجم انجام نشد! نمیدونم که مشکل از API هست یا خود پنل ولی احتمال بالا مشکل از API هست.



> سلام وقت بخیر. وقتی کلاینت با استفاده از این API و مدل سنائی اضافه میکنم یه مشکلی به وجود میاد. رفتم بررسی کردم دیدم وقتی از داخل پنل یوزر ساخته بشه داخل جدول clients_traffic هم اون یوزر ساخته میشه و اونجوری محاسبه حجم هم انجام میشه. ولی وقتی با استفاده از این API این کار میکنم یوزر داخل جدول clients_traffic ساخته نمیشه و خب محاسبه حجم هم انجام نمیشه. البته حتی وقتی دستی هم رفتم یوزر تو این جدول اضافه کردم باز هم محاسبه حجم انجام نشد! نمیدونم که مشکل از API هست یا خود پنل ولی احتمال بالا مشکل از API هست.

سلام از 
متد https://github.com/alirezax5/xuiapi/blob/main/Examples/addClient.php استفاده میکنید؟

**Comment by sajjad5221** [comment]
> > سلام وقت بخیر. وقتی کلاینت با استفاده از این API و مدل سنائی اضافه میکنم یه مشکلی به وجود میاد. رفتم بررسی کردم دیدم وقتی از داخل پنل یوزر ساخته بشه داخل جدول clients_traffic هم اون یوزر ساخته میشه و اونجوری محاسبه حجم هم انجام میشه. ولی وقتی با استفاده از این API این کار میکنم یوزر داخل جدول clients_traffic ساخته نمیشه و خب محاسبه حجم هم انجام نمیشه. البته حتی وقتی دستی هم رفتم یوزر تو این جدول اضافه کردم باز هم محاسبه حجم انجام نشد! نمیدونم که مشکل از API هست یا خود پنل ولی احتمال بالا مشکل از API هست.
> 
> > سلام وقت بخیر. وقتی کلاینت با استفاده از این API و مدل سنائی اضافه میکنم یه مشکلی به وجود میاد. رفتم بررسی کردم دیدم وقتی از داخل پنل یوزر ساخته بشه داخل جدول clients_traffic هم اون یوزر ساخته میشه و اونجوری محاسبه حجم هم انجام میشه. ولی وقتی با استفاده از این API این کار میکنم یوزر داخل جدول clients_traffic ساخته نمیشه و خب محاسبه حجم هم انجام نمیشه. البته حتی وقتی دستی هم رفتم یوزر تو این جدول اضافه کردم باز هم محاسبه حجم انجام نشد! نمیدونم که مشکل از API هست یا خود پنل ولی احتمال بالا مشکل از API هست.
> 
> سلام از متد https://github.com/alirezax5/xuiapi/blob/main/Examples/addClient.php استفاده میکنید؟

بله. همچین کدیه:
    $list = $xui->listInbound();
    $lastId = end($list["obj"])['id'];
    $xui->addnewClient($lastId, $uuidString, $email, 'flow', $TRAFFIC, $expiryTime, 1, 'chrome', false);

**Comment by alirezax5** [comment]
> > > سلام وقت بخیر. وقتی کلاینت با استفاده از این API و مدل سنائی اضافه میکنم یه مشکلی به وجود میاد. رفتم بررسی کردم دیدم وقتی از داخل پنل یوزر ساخته بشه داخل جدول clients_traffic هم اون یوزر ساخته میشه و اونجوری محاسبه حجم هم انجام میشه. ولی وقتی با استفاده از این API این کار میکنم یوزر داخل جدول clients_traffic ساخته نمیشه و خب محاسبه حجم هم انجام نمیشه. البته حتی وقتی دستی هم رفتم یوزر تو این جدول اضافه کردم باز هم محاسبه حجم انجام نشد! نمیدونم که مشکل از API هست یا خود پنل ولی احتمال بالا مشکل از API هست.
> > 
> > 
> > > سلام وقت بخیر. وقتی کلاینت با استفاده از این API و مدل سنائی اضافه میکنم یه مشکلی به وجود میاد. رفتم بررسی کردم دیدم وقتی از داخل پنل یوزر ساخته بشه داخل جدول clients_traffic هم اون یوزر ساخته میشه و اونجوری محاسبه حجم هم انجام میشه. ولی وقتی با استفاده از این API این کار میکنم یوزر داخل جدول clients_traffic ساخته نمیشه و خب محاسبه حجم هم انجام نمیشه. البته حتی وقتی دستی هم رفتم یوزر تو این جدول اضافه کردم باز هم محاسبه حجم انجام نشد! نمیدونم که مشکل از API هست یا خود پنل ولی احتمال بالا مشکل از API هست.
> > 
> > 
> > سلام از متد https://github.com/alirezax5/xuiapi/blob/main/Examples/addClient.php استفاده میکنید؟
> 
> بله. همچین کدیه: $list = $xui->listInbound(); $lastId = end($list["obj"])['id']; $xui->addnewClient($lastId, $uuidString, $email, 'flow', $TRAFFIC, $expiryTime, 1, 'chrome', false);

اول اینکه flow خالی بزار وگرنه خطا میخوری جز اینکه بخوای xtls و vision استفاده کنی
و بنظرم همون نمونه رو کپی کردید که از کلاس Vaxilu گرفته شده , و احتمالا از ثنایی استفاده میکنید برای ثنایی و علیرضا به جای 
```php
$xui = new \alirezax5\XuiApi\Panel\Vaxilu('YOU_PANEL_URL', 'YOU_PANEL_USERNAME', 'YOU_PANEL_PASSWORD');
```
از :
```php
$xui = new \alirezax5\XuiApi\Panel\MHSanaei('YOU_PANEL_URL', 'YOU_PANEL_USERNAME', 'YOU_PANEL_PASSWORD');
```
استفاده کنید
