### ISSUE TITLE
راهنمایی جهت استفاده اولیه

### ISSUE THREAD

**Issue by xxamr** [alirezax5/xuiapi#16]
سلام
ممنون میشم مقداری راهنمایی کنید جهت استفاده.
من با داکر نصب کردم. ولی نمیدونم ادامه اش را باید چه کار کنم؟

**Comment by alirezax5** [comment]
> سلام ممنون میشم مقداری راهنمایی کنید جهت استفاده. من با داکر نصب کردم. ولی نمیدونم ادامه اش را باید چه کار کنم؟

این سورس رو یا xui?

**Comment by xxamr** [comment]
سورس شما را

**Comment by alirezax5** [comment]
> سورس شما را

تاحالا سمت داکر نرفتم و از ظریق کامپوزر سورس رو دانلود کنید بعد توی داکر اجراش کردید ؟
طبق نمونه اخر یک index با زبان php بسازید و تستش کنید
