### ISSUE TITLE
پارامتر

### ISSUE THREAD

**Issue by sinahinson** [alirezax5/xuiapi#17]
درود
پارامتر هارو توضیح میدید 
-MHSanaei

**Comment by alirezax5** [comment]
> درود پارامتر هارو توضیح میدید -MHSanaei

سلام برای ایجاد شی؟ به ترتیب ادرس پنل ، نام کاربری ، رمز پنل

**Comment by sinahinson** [comment]
کامل بگید چطوری و میخام اطلاعات کاربر از ایمیل نشون بده همین

**Comment by alirezax5** [comment]
> کامل بگید چطوری و میخام اطلاعات کاربر از ایمیل نشون بده همین

سلام فردا ی متد ساده براش میزارم توی سورس
