### ISSUE TITLE
خطای 404 در گرفتن لیست اینباند

### ISSUE THREAD

**Issue by alimhmd2776** [alirezax5/xuiapi#18]
با عرض سلام و خسته نباشید! 

بنده در لوکال دارم تست میکنم و مشکلی که دارم به عنوان مثال listInbound مقدار برگشتی نال هست و وقتی خروجی curl رو چاپ کردم خطای 404 میده! 
چک کردم path ارسالی هم درست هست !! 

بنظر مشکل کجاست؟

**Comment by alirezax5** [comment]
> با عرض سلام و خسته نباشید!
> 
> بنده در لوکال دارم تست میکنم و مشکلی که دارم به عنوان مثال listInbound مقدار برگشتی نال هست و وقتی خروجی curl رو چاپ کردم خطای 404 میده! چک کردم path ارسالی هم درست هست !!
> 
> بنظر مشکل کجاست؟

سلام پنلتون چیه و کدتون هم بفرستید
