### ISSUE TITLE
ایراد در پنل صناعی

### ISSUE THREAD

**Issue by elegance666** [alirezax5/xuiapi#19]
سلام، ورژن قبلی تر کارا بود الان موقع addnewClientاطلاعاتی که بر میگردونه خیلی ناقص و کم شده

**Comment by alirezax5** [comment]
> سلام، ورژن قبلی تر کارا بود الان موقع XUI_createUser اطلاعاتی که بر میگردونه خیلی ناقص و کم شده

سلام چیاش کم شده؟

**Comment by elegance666** [comment]
قبلا اینا برمیگردوند

['success'] = Boolean(1) TRUE
['msg'] = String(12) "修改成功"
 ['obj'] => Array (15)
(
['id'] = Integer(1) 7
['up'] = Integer(8) 30284036
['down'] = Integer(9) 617954600
['total'] = Integer(1) 0
['remark'] = String(12) "GRPC-Reality"
['enable'] = Boolean(1) TRUE
['expiryTime'] = Integer(1) 0
['clientStats'] = NULL(0) NULL
['listen'] = String(0) ""
['port'] = Integer(4) 8443
['protocol'] = String(5) "vless"
['settings'] = String(1910) "{"clients":[{"email":..,"fallbacks":[]}"
['streamSettings'] = String(479) "{"network":"tcp","security":"reality","realitySettings":{"show":false,"xver":0,"dest":"...:443","serverNames":["...","...."],"privateKey":"....","minClient":"","maxClient":"","maxTimediff":0,"shortIds":["e713aece"],"settings":{"publicKey":"oScijJ6m6gsPrEkqOA7d6HYfs8GNwpdNomRUIWl2rS0","fingerprint":"firefox","serverName":""}},"tcpSettings":{"acceptProxyProtocol":false,"header":{"type":"none"}}}"
['tag'] = String(0) ""
['sniffing'] = String(53) "{"enabled":true,"destOverride":["http","tls","quic"]}"
)




ولی الان فقط شده این:

['success'] = Boolean(1) TRUE
['msg'] = String(22) "Client(s) addedSuccess"
['obj'] = NULL(0) NULL

**Comment by alirezax5** [comment]
> 

برای اینکه مصرف کم بشه از متد خود سنایی استفاده شده که این پیغام برگشتی از پنل سناییه.
مدل قبلی تعداد بالا فشار میوورد هم به پنل هم به سورسی که اجرا میشه

**Comment by alirezax5** [comment]
> قبلا اینا برمیگردوند
> 
> ['success'] = Boolean(1) TRUE ['msg'] = String(12) "修改成功" ['obj'] => Array (15) ( ['id'] = Integer(1) 7 ['up'] = Integer(8) 30284036 ['down'] = Integer(9) 617954600 ['total'] = Integer(1) 0 ['remark'] = String(12) "GRPC-Reality" ['enable'] = Boolean(1) TRUE ['expiryTime'] = Integer(1) 0 ['clientStats'] = NULL(0) NULL ['listen'] = String(0) "" ['port'] = Integer(4) 8443 ['protocol'] = String(5) "vless" ['settings'] = String(1910) "{"clients":[{"email":..,"fallbacks":[]}" ['streamSettings'] = String(479) "{"network":"tcp","security":"reality","realitySettings":{"show":false,"xver":0,"dest":"...:443","serverNames":["...","...."],"privateKey":"....","minClient":"","maxClient":"","maxTimediff":0,"shortIds":["e713aece"],"settings":{"publicKey":"oScijJ6m6gsPrEkqOA7d6HYfs8GNwpdNomRUIWl2rS0","fingerprint":"firefox","serverName":""}},"tcpSettings":{"acceptProxyProtocol":false,"header":{"type":"none"}}}" ['tag'] = String(0) "" ['sniffing'] = String(53) "{"enabled":true,"destOverride":["http","tls","quic"]}" )
> 
> ولی الان فقط شده این:
> 
> ['success'] = Boolean(1) TRUE ['msg'] = String(22) "Client(s) addedSuccess" ['obj'] = NULL(0) NULL

برای اینکه مصرف کم بشه از متد خود سنایی استفاده شده که این پیغام برگشتی از پنل سناییه.
مدل قبلی تعداد بالا فشار میوورد هم به پنل هم به سورسی که اجرا میشه

**Comment by elegance666** [comment]
خوب اینکه publicKey, shortid, sni و خیلی چیزای دیگه برنمیگردونه، یوزر اضافه میشه ولی نمیشه اطلاعاتش خوند....

**Comment by elegance666** [comment]
همون مدل قبلی صناعی خوب بود فقط کافی بود آدرس از xui به پنل عوض بشه، الان من خیلی وقته نتونستم از v1.4.1 آپدیت برم جلوتر...

**Comment by alirezax5** [comment]
> خوب اینکه publicKey, shortid, sni و خیلی چیزای دیگه برنمیگردونه، یوزر اضافه میشه ولی نمیشه اطلاعاتش خوند....

این اطلاعات رو شما قبلا ایجاد کردید و بهتره داخل یک دیتابیس ثبت کنید ، موقع ساختن کاربر اطلاعات inbound رو از دیتابیس  واکشی کنید برای ساخت لینک.
یعنی شما دیتابیسی دارید به اسم inbound 
موقعی که خواستید برای این inbound یوزر بسازید به وسیله ایدیش توی دیتابیستون چک میکنید sni و کلید های خصوصی و عمومی چیه و با uuid جدید کاربر لینک میسازید.

اگه به این روش نیاز ندارید میتونید از بخش نسخه ها اپدیت های قبلی رو دانلود کنید و بخش ویرایش کاربرش رو بردارید و‌توی سورس جدیدتر بزارید

**Comment by elegance666** [comment]
تو کدوم ورژن از قبلی‌ها برای صناعی اطلاعات کامل برمیگردونه؟

**Comment by alirezax5** [comment]
> تو کدوم ورژن از قبلی‌ها برای صناعی اطلاعات کامل برمیگردونه؟

فکر کنم 1.5.10 اوکی باشه برات

**Comment by elegance666** [comment]
باشه، ممنون امتحان میکنم
