### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by mostafa9112** [alirezax5/xuiapi#2]
hi.
it's not working.
can you send an example?

**Comment by alirezax5** [comment]
> hi. it's not working. can you send an example?

Hello, do you work in localhost or environments like cpanel?
If you work in cpanel or directadmin, you must open the port you chose for xui in the firewall.

Also, if you have filled in the path, you must also write it.

Sample :
$xui = new \alirezax5\XuiApi\Panel\Vaxilu('192.1.1.1:2020/path ', 'YOU_PANEL_USERNAME', 'YOU_PANEL_PASSWORD');

**Comment by alirezax5** [comment]
> tnx dude. can you help me for get connected ip address to proxy for niduka and asadi panel?
> 
> or worked way for ip limit?

Read the following address:
https://github.com/HexaSoftwareTech/x-ui#enable-ip-restrictions-per-inbound

The panel below also supports device limitations
https://github.com/FranzKafkaYu/x-ui/

Note: This method does not work in the forwarding method with iptabel and cloudflare proxy

**Comment by mostafa9112** [comment]
> > tnx dude. can you help me for get connected ip address to proxy for niduka and asadi panel?
> > or worked way for ip limit?
> 
> Read the following address: https://github.com/HexaSoftwareTech/x-ui#enable-ip-restrictions-per-inbound
> 
> The panel below also supports device limitations https://github.com/FranzKafkaYu/x-ui/
> 
> Note: This method does not work in the forwarding with iptabel and cloudflare proxy

tnx but i need ip limitation by client

**Comment by alirezax5** [comment]
Then use niduka or asadi (HexaSoftwareTech) panel and add the json code to xray config:

```json
"log": {
   "loglevel": "warning", 
   "access": "./access.log"
 }, 
```

and Restart xray

**Comment by alirezax5** [comment]
> > > tnx dude. can you help me for get connected ip address to proxy for niduka and asadi panel?
> > > or worked way for ip limit?
> > 
> > 
> > Read the following address: https://github.com/HexaSoftwareTech/x-ui#enable-ip-restrictions-per-inbound
> > The panel below also supports device limitations https://github.com/FranzKafkaYu/x-ui/
> > Note: This method does not work in the forwarding with iptabel and cloudflare proxy
> 
> tnx but i need ip limitation by client

Then use niduka or asadi (HexaSoftwareTech) panel and add the json code to xray config:

```json
"log": {
   "loglevel": "warning", 
   "access": "./access.log"
 }, 
```

and Restart xray

**Comment by mostafa9112** [comment]
this is my config but still iplimit not working

`{
  "log": {
    "loglevel": "warning", 
    "access": "./access.log"
  },
 
  "api": {
    "services": [
      "HandlerService",
      "LoggerService",
      "StatsService"
    ],
    "tag": "api"
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": 62789,
      "protocol": "dokodemo-door",
      "settings": {
        "address": "127.0.0.1"
      },
      "tag": "api"
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "settings": {}
    },
    {
      "protocol": "blackhole",
      "settings": {},
      "tag": "blocked"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundDownlink": true,
      "statsInboundUplink": true
    }
  },
  "routing": {
    "rules": [
      {
        "inboundTag": [
          "api"
        ],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "blocked",
        "type": "field"
      },
      {
        "outboundTag": "blocked",
        "protocol": [
          "bittorrent"
        ],
        "type": "field"
      }
    ]
  },
  "stats": {}
}
`

**Comment by alirezax5** [comment]
> 

When I tried it before, it worked correctly, don't you enter each client's email repeatedly?

**Comment by mostafa9112** [comment]
No emails and ClientIDs are unique

**Comment by alirezax5** [comment]
> No emails and ClientIDs are unique

You must choose a unique email for each client
