### ISSUE TITLE
expire_date فرمت

### ISSUE THREAD

**Issue by elegance666** [alirezax5/xuiapi#20]
برای ساخت یوزر expire_date باید با چه فانکشن یا فرمتی ساخته بشه؟ این فرمت کار نمیکنه 2023-07-14 21:32:16

**Comment by alirezax5** [comment]
سلام میلی ثانیس

> برای ساخت یوزر expire_date باید با چه فانکشن یا فرمتی ساخته بشه؟ این فرمت کار نمیکنه 2023-07-14 21:32:16
