### ISSUE TITLE
بعد از ساخت اکانت Subscription کار نمیکنه

### ISSUE THREAD

**Issue by elegance666** [alirezax5/xuiapi#21]
سلام،
در پنل صانعی، بعد از ساخت اکانت Subscription لینک Error! میده ولی وقتی یکبار دستی همون یوزر رو ویرایش Save change رو میزنی لینک سابسکرایب درست میشه!

**Comment by alirezax5** [comment]
> سلام، در پنل صانعی، بعد از ساخت اکانت Subscription لینک Error! میده ولی وقتی یکبار دستی همون یوزر رو ویرایش Save change رو میزنی لینک سابسکرایب درست میشه!

یک عکس از بخشش بدید

**Comment by elegance666** [comment]
![image](https://github.com/alirezax5/xuiapi/assets/23729575/8448b5fa-2ac1-4b3f-bff5-923702c6a796)
این اکانت با API شما ساخته، که بعد از کلیک روی لینک sub ساخته شده این صفحه میاد 
![image](https://github.com/alirezax5/xuiapi/assets/23729575/a67ad627-24dc-4e26-ac7f-b82e477af13a)
ولی بعد از اینکه یکبار داخل پنل یوز سیو بشه لینک کار میکنه و کاتفیگ مربوط رو نمایش میده

**Comment by elegance666** [comment]
البته قبلش تو پنل صانعی قسمت تنطیمات Subscription فعال و یک پورت هم بهش اختصاص داده شده

**Comment by alirezax5** [comment]
> البته قبلش تو پنل صانعی قسمت تنطیمات Subscription فعال و یک پورت هم بهش اختصاص داده شده

توی این مدت سرم شلوغ بوده
اخر هفته چکش میکنم

**Comment by elegance666** [comment]
ممنونم

**Comment by elegance666** [comment]
سلام تو ورژن جدید صانعی 1.7.1 دیگه کلا با API شما یوزر میسازی کار نمیکنه، مگر اینکه یکبار دستی تو پنل یوزر ادیت و سیو بشه...

**Comment by elegance666** [comment]
ضمنا لطفا آدرس USDT هم بزار که هرکس تونست دونیت کنه

**Comment by alirezax5** [comment]
> ![image](https://user-images.githubusercontent.com/23729575/253519414-8448b5fa-2ac1-4b3f-bff5-923702c6a796.png) این اکانت با API شما ساخته، که بعد از کلیک روی لینک sub ساخته شده این صفحه میاد ![image](https://user-images.githubusercontent.com/23729575/253519707-a67ad627-24dc-4e26-ac7f-b82e477af13a.png) ولی بعد از اینکه یکبار داخل پنل یوز سیو بشه لینک کار میکنه و کاتفیگ مربوط رو نمایش میده

حل شد

**Comment by elegance666** [comment]
ممنون درست شده روی ۱.۷.۰ لینک عضویت، ولی روی ۱.۷.۱ کاربر ساخته شده با API کار نمیکنه و اررور Fail to detect ineternet connection: EOF میده، تا زمانی که یکبار دستی از تو پنل کاربر اضافه شده save بشه...

**Comment by alirezax5** [comment]
> ممنون درست شده روی ۱.۷.۰ لینک عضویت، ولی روی ۱.۷.۱ کاربر ساخته شده با API کار نمیکنه و اررور Fail to detect ineternet connection: EOF میده، تا زمانی که یکبار دستی از تو پنل کاربر اضافه شده save بشه...

پنل سنایی عجایب زیاد داره ، چک کن qr با اطلاعاتی که ارسال کردی یکیه؟

**Comment by elegance666** [comment]
میخوای پنل بدم تست کنی خودت؟

![qrcode](https://github.com/alirezax5/xuiapi/assets/23729575/dcbd2b4a-e084-4664-af3a-28f1a2f8f515)
این الان با API شما ساخته شده ولی دستی تو پنل یوزر سیو نشده

**Comment by elegance666** [comment]
روی 1.7.0 درست کار میکنه ولی 1.7.1 اینطوری شده

**Comment by alirezax5** [comment]
> میخوای پنل بدم تست کنی خودت؟
> 
> ![qrcode](https://user-images.githubusercontent.com/23729575/255216946-dcbd2b4a-e084-4664-af3a-28f1a2f8f515.png) این الان با API شما ساخته شده ولی دستی تو پنل یوزر سیو نشده

کلاینت جدید میسازی ، بعد qr ش کار نمیده؟

**Comment by elegance666** [comment]
اره، ولی وقتی یکبار دستی ادیت کنم و سیو بزنم روش درست میشه

**Comment by alirezax5** [comment]
> اره، ولی وقتی یکبار دستی ادیت کنم و سیو بزنم روش درست میشه

اگه میتونید ی بار با api بساز بعد دیتابیس چک کن کلاینته اضافه شده یا ن

**Comment by elegance666** [comment]
اره اضافه میشه تو پنل میبینمش، فقط تا قبل از یکبار سیو شدن تو پنل کار نمیکنه

**Comment by elegance666** [comment]
شبیه همون لینک سابسکرایب که درست کردین ولی اینبار روی خود اکانت....

**Comment by alirezax5** [comment]
> شبیه همون لینک سابسکرایب که درست کردین ولی اینبار روی خود اکانت....


تست کردم کلاینت جدید کار میکنه

**Comment by elegance666** [comment]
برای من رو ۱.۷.۱ کار یوزر ساخته شده با API نمیکنه ولی ۱.۷.۰ درسته...

**Comment by elegance666** [comment]
الان دیدم SubId اضافه کردین صبر کنید با اون چک کنم

**Comment by elegance666** [comment]
آقا درسته عذر میخوام، من از example قبلی استفاده میکردم subid و tgid نمیزاشتم.
درست کار میکنه الا
