### ISSUE TITLE
عدم اتصال به سرور مقصد

### ISSUE THREAD

**Issue by alimhmd2776** [alirezax5/xuiapi#23]
خسته نباشید
متاسفانه من نه از طریق لوکال و نه از طریق سرور نتونستم موفق به دریافت اطلاعات از سمت سرور v2ray بشم.
مدل پنل NidukaAkalanka
پورت پنل باز شده است روی فایروال
کوکی رو پاک کردم نشد
هر فانکشنی که اجرا میکنم فقط false بر میگردونه 
سرور سایتم ubuntu22.04 و روی apache2
و البته ای پی به سی دی ان آروان متصل شده است

**Comment by alirezax5** [comment]
> خسته نباشید متاسفانه من نه از طریق لوکال و نه از طریق سرور نتونستم موفق به دریافت اطلاعات از سمت سرور v2ray بشم. مدل پنل NidukaAkalanka پورت پنل باز شده است روی فایروال کوکی رو پاک کردم نشد هر فانکشنی که اجرا میکنم فقط false بر میگردونه سرور سایتم ubuntu22.04 و روی apache2 و البته ای پی به سی دی ان آروان متصل شده است

سلام کدتونو بفرستید
به جای ip ایکس بزارید
