### ISSUE TITLE
دریافت تنظیمات نهایی برای کاربر 

### ISSUE THREAD

**Issue by esmaei1** [alirezax5/xuiapi#24]
چگونه می توان تظیمات مربوط به یک کاربر را که در نهایت در نرم افزار v2ry وارد میشود را دریافت کرد. تنظمیاتی شبیه این که توسط qrcode هم در پنل نمایش داده می شود:
vless://08a3840e-5632-4c5b-b2e6-baf9c5ec7f36@77.258.18.21:51050?type=tcp&security=none#vless_tcp-negqoz0s
 یا به عبارتی همان url

**Comment by alirezax5** [comment]
> چگونه می توان تظیمات مربوط به یک کاربر را که در نهایت در نرم افزار v2ry وارد میشود را دریافت کرد. تنظمیاتی شبیه این که توسط qrcode هم در پنل نمایش داده می شود: vless://08a3840e-5632-4c5b-b2e6-baf9c5ec7f36@77.258.18.21:51050?type=tcp&security=none#vless_tcp-negqoz0s یا به عبارتی همان url

سلام از کجا میخواید دریافت کنید؟

**Comment by esmaei1** [comment]
سلام. از سروری که پنل روی آن نصب است. به کمک این api که شما نوشته اید. مثلا یک متد هست به اسم getClientData که اگر ایدی کلاینت را به آن به دهید اطلاعات آن را می دهد. ولی این اطلاعات شامل url ی که گفتم نیست. می خواستم بدانم روشی هست که این url را هم دریافت کنیم برای کاربر؟

**Comment by alirezax5** [comment]
> سلام. از سروری که پنل روی آن نصب است. به کمک این api که شما نوشته اید. مثلا یک متد هست به اسم getClientData که اگر ایدی کلاینت را به آن به دهید اطلاعات آن را می دهد. ولی این اطلاعات شامل url ی که گفتم نیست. می خواستم بدانم روشی هست که این url را هم دریافت کنیم برای کاربر؟

داخل سورس چیزی برای این مورد قرار ندادم و باید براساس داده های کاربر بسازیدش

**Comment by esmaei1** [comment]
ممنون. اگر اضافه کنید یا این که توضیح بدید که خودم چطور میتونم اضافه کنم خیلی خوب میشه. تشکر

**Comment by alirezax5** [comment]
> ممنون. اگر اضافه کنید یا این که توضیح بدید که خودم چطور میتونم اضافه کنم خیلی خوب میشه. تشکر

اگه php بلد باشید فقط ساختار رو آماده کنید اطلاعات کاربر رو جایگزین لینک کنید

**Comment by esmaei1** [comment]
در بعضی موارد مثل vmess آدرس ایجاد شده هش شده است و نمیشه بر اساس داده های دریافتی درست کرد. مثلا برای vmess tcp یه همجین آدرسی ایجاد میشه در پنل:
vmess://ewogICJ2IjogIjIiLAogICJwcyI6ICJ2bWVzc190Y3AtMWh0em1oeGMiLAogICJhZGQiOiAiOTQuMTMxLjEyLjIyMSIsCiAgInBvcnQiOiAxMDk3MSwKICAiaWQiOiAiNTcxMjhlZ5ktNTY5MS00Mzk4LWE2NjUtZGM1Zjg4YTdjZjUyIiwKICAibmV0IjogInRjcCIsCiAgInR5cGUiOiAibm9uZSIsCiAgInRscyI1ICJub25lIgp9

**Comment by alirezax5** [comment]
> در بعضی موارد مثل vmess آدرس ایجاد شده هش شده است و نمیشه بر اساس داده های دریافتی درست کرد. مثلا برای vmess tcp یه همجین آدرسی ایجاد میشه در پنل: vmess://ewogICJ2IjogIjIiLAogICJwcyI6ICJ2bWVzc190Y3AtMWh0em1oeGMiLAogICJhZGQiOiAiOTQuMTMxLjEyLjIyMSIsCiAgInBvcnQiOiAxMDk3MSwKICAiaWQiOiAiNTcxMjhlZ5ktNTY5MS00Mzk4LWE2NjUtZGM1Zjg4YTdjZjUyIiwKICAibmV0IjogInRjcCIsCiAgInR5cGUiOiAibm9uZSIsCiAgInRscyI1ICJub25lIgp9

محتواش json هستش میتونید داخل یک رشته قرار بدید و با یک کاراکتر خاص و strtr داده هارو جایگزین کنید
بعد base64_encode کنید
