### ISSUE TITLE
خواندن میزان مصرف شده

### ISSUE THREAD

**Issue by elegance666** [alirezax5/xuiapi#25]
سلامی دوباره، 
تو پنل صانعی  xui->getClientData  میزان حجم مصرف شده برنمیگردونه، getClientTraffics($email) هم اصلا کار نمیکنه چون inboud_id نمیگیره!!!
کلا حجم مصرف شده رو نمیشه خوند.

**Comment by alirezax5** [comment]
> سلامی دوباره، تو پنل صانعی xui->getClientData میزان حجم مصرف شده برنمیگردونه، getClientTraffics($email) هم اصلا کار نمیکنه چون inboud_id نمیگیره!!! کلا حجم مصرف شده رو نمیشه خوند.

سلام اینترنتم بهتر بشه چکش میکنم

**Comment by alirezax5** [comment]
> سلامی دوباره، تو پنل صانعی xui->getClientData میزان حجم مصرف شده برنمیگردونه، getClientTraffics($email) هم اصلا کار نمیکنه چون inboud_id نمیگیره!!! کلا حجم مصرف شده رو نمیشه خوند.

توی نسخه https://github.com/alirezax5/xuiapi/releases/tag/1.10.18 حل شد

**Comment by elegance666** [comment]
دست مریزاد، خسته نباشید چک میکنم شب خونه رسید، ممنون از شما.
