### ISSUE TITLE
خطای 500

### ISSUE THREAD

**Issue by Saeedg21** [alirezax5/xuiapi#26]
سلام خسته نباشید
من چرا همش خطای 500 از سمت سرور هاست میگیرم ؟

**Comment by alirezax5** [comment]
> سلام خسته نباشید من چرا همش خطای 500 از سمت سرور هاست میگیرم ؟

سلام باید فایل error_log رو نگاه کنید تا متوجه بشید

**Comment by Saeedg21** [comment]
متاسفانه فایل لاگ ایجاد نمیکنه
اگه مقدور باشه نحوه نصبش رو بگین ممنون میشم

**Comment by alirezax5** [comment]
> متاسفانه فایل لاگ ایجاد نمیکنه اگه مقدور باشه نحوه نصبش رو بگین ممنون میشم

باید اول با کامپوزر پکیج هارو به دستور زیر نصب کنید
https://github.com/alirezax5/xuiapi#install
بعد پوششو‌انتقال بدید به هاستتون

**Comment by Saeedg21** [comment]
ممنونم و سپاسگزارم بابت راهنمایی سریعتان 
 طبق فرمایشات شما انجام دادم 
اول composer نصب کردم
دوم composer require alirezax5/xuiapi این دستور را اجرا کردم
سوم در سمت سرور 3x-ui همه فایل ها رو به حالت zip تبدیل و دانلود کردم
چهارم فایل های دانلود شده را در یک هاست دیگه ای اپلود و برای مثال صفحه vendor/alirezax5/xuiapi/Examples/listInbound.php را اجرا کردم
پنچم باز خطای 500 رو داد

This page isn’t working *.com is currently unable to handle this request.
HTTP ERROR 500

**Comment by alirezax5** [comment]
> ممنونم و سپاسگزارم بابت راهنمایی سریعتان طبق فرمایشات شما انجام دادم اول composer نصب کردم دوم composer require alirezax5/xuiapi این دستور را اجرا کردم سوم در سمت سرور 3x-ui همه فایل ها رو به حالت zip تبدیل و دانلود کردم چهارم فایل های دانلود شده را در یک هاست دیگه ای اپلود و برای مثال صفحه vendor/alirezax5/xuiapi/Examples/listInbound.php را اجرا کردم پنچم باز خطای 500 رو داد
> 
> This page isn’t working *.com is currently unable to handle this request. HTTP ERROR 500

اونا نمونه کدن
باید یک فایل کنار پوشه vendor بسازید

**Comment by Saeedg21** [comment]
سلام مجدد

بازم مشکلم رفع نشد متاسفانه

هر فایلی که داخل پوشه panel هست رو اجرا میکنم خطای 500 میده من که از پنل 3x-ui استفاده میکنم کلاس MHSanaei رو استفاده میکنم که اینم خطا داره

ورژن PHP باید چند باشه ؟
و اینکه PHP Extensions غیر از curl چیز دیگه ای نیاز داره ؟

ممنونم از راهنمایی تان

**Comment by alirezax5** [comment]
> سلام مجدد
> 
> بازم مشکلم رفع نشد متاسفانه
> 
> هر فایلی که داخل پوشه panel هست رو اجرا میکنم خطای 500 میده من که از پنل 3x-ui استفاده میکنم کلاس MHSanaei رو استفاده میکنم که اینم خطا داره
> 
> ورژن PHP باید چند باشه ؟ و اینکه PHP Extensions غیر از curl چیز دیگه ای نیاز داره ؟
> 
> ممنونم از راهنمایی تان

مگه php کار نیستید ؟ اصلا نیاز نیست پوشه panel رو اجرا کنید فقط در کنار پوشه vendor یک فایل بسازید و از مثال ها استفاده کنید

**Comment by Saeedg21** [comment]
سپاسگزارم مورد رفع شد ممنونم
