### ISSUE TITLE
روش نصب رو هاست

### ISSUE THREAD

**Issue by yhsoft3** [alirezax5/xuiapi#28]
سلام میشه توضیح بدین چطور  رو هاست نصبش کنم

**Comment by Saeedg21** [comment]
مرحله اول composer  رو در سرور نصب کنین
مرحله دوم از دستور composer require alirezax5/xuiapi برای نصب استفاده کنین
مرحله سوم فایل های دانلود شده در سمت سرور که معمولا رد فولدر ROOT قرار داره رو به سیستم شخصی انتقال بدین

**Comment by alirezax5** [comment]
> سلام میشه توضیح بدین چطور رو هاست نصبش کنم

سلام چیزی که دوستمون گفت
فقط باید روی سیستم کامپزر نصب کنید بعد فایل هاتونو به هاست انتقال بدیذ

**Comment by Saeedg21** [comment]
و دیگه اینکه ورژن PHP هاست یا لوکال بزرگتر برابر 7.5 باید باشه
