### ISSUE TITLE
عدم کارکرد $_REQUEST , $_GET

### ISSUE THREAD

**Issue by Saeedg21** [alirezax5/xuiapi#29]
سلام 
من مثل لینک زیر پارامتری به API ارسال میکنم که کار نمیکنه
http://XXX.xxx.XXX.xxx/getClient.php?Inbund=1&Email=Email
$Inbud = $_GET['Inbund'];
$Email= $_GET['Email'];
Or
$Inbud = $_REQUEST['Inbund'];
$Email= $_REQUEST['Email'];

$xui->getClientDataByEmail( $Inbund,$Email);
میخوام با استفاده از Inbund و Email ارسالی به سمت سرور اطلاعات دریافت و نمایش داده بشه که اینکار انجام نمیشه
ولی اگه مثل زیر دستی بدم کار میکنه
$Inbud = 1;
$Email= 'Email';

$xui->getClientDataByEmail( $Inbund,$Email);

میشه در این مورد راهنمایی کنین ؟

**Comment by alirezax5** [comment]
> سلام من مثل لینک زیر پارامتری به API ارسال میکنم که کار نمیکنه http://XXX.xxx.XXX.xxx/getClient.php?Inbund=1&Email=Email $Inbud = $_GET['Inbund']; $Email= $_GET['Email']; Or $Inbud = $_REQUEST['Inbund']; $Email= $_REQUEST['Email'];
> 
> $xui->getClientDataByEmail( $Inbund,$Email); میخوام با استفاده از Inbund و Email ارسالی به سمت سرور اطلاعات دریافت و نمایش داده بشه که اینکار انجام نمیشه ولی اگه مثل زیر دستی بدم کار میکنه $Inbud = 1; $Email= 'Email';
> 
> $xui->getClientDataByEmail( $Inbund,$Email);
> 
> میشه در این مورد راهنمایی کنین ؟

سلام خطای چیزی نداره؟ و متغیر های get هم echo کنید ببینید صحیح پاس داده میشه؟

**Comment by Saeedg21** [comment]
سلام 
هیچ خطایی نمیده و پیغام false برگشت داده میشه 
بلی Echo کردنی اطلاعات پاس شده نمایش داده میشه جالب

**Comment by alirezax5** [comment]
> سلام هیچ خطایی نمیده و پیغام false برگشت داده میشه بلی Echo کردنی اطلاعات پاس شده نمایش داده میشه جالب

Inbund
رو int کنید و تستش کنید
الان مسافرتم نمیتونم با سیستم بررسیش کنم

**Comment by Saeedg21** [comment]
✅✅✅
انجام شد و درست شد
مسافرت خوش بگذره
