### ISSUE TITLE
listInbound

### ISSUE THREAD

**Issue by elegance666** [alirezax5/xuiapi#30]
امروز اومدم اسکریپت رو تست کنم دیدم اینسری listInbound کار نمیکنه رو پنل صانعی

$xui->login(true);
$xui->listInbound();

**Comment by alirezax5** [comment]
> امروز اومدم اسکریپت رو تست کنم دیدم اینسری listInbound کار نمیکنه رو پنل صانعی
> 
> $xui->login(true); $xui->listInbound();

سلام این چند هفته اینترنتم مشکل داره

نسخه اخر مشکلو داره؟
