### ISSUE TITLE
تا چه ورژنی از پنل هارو پشتیبانی میکنه

### ISSUE THREAD

**Issue by MortezaRajabzadeh** [alirezax5/xuiapi#31]
سلام عزیز وقتت بخیر ممنون بابت پروژه ی خوبت 
من از addnewClient استفاده میکنم یوزر ساخته میشه ولی تو پنل ارور میده از نمونه کد های خودتونم استفاده کردم همینطور بود 
ورژن پنلی که تست کردم ثنایی 2.0.2 و 1.7.9 بوده راهنمایی میفرمایید

**Comment by alirezax5** [comment]
> سلام عزیز وقتت بخیر ممنون بابت پروژه ی خوبت من از addnewClient استفاده میکنم یوزر ساخته میشه ولی تو پنل ارور میده از نمونه کد های خودتونم استفاده کردم همینطور بود ورژن پنلی که تست کردم ثنایی 2.0.2 و 1.7.9 بوده راهنمایی میفرمایید

سلام کداتونو بفرستید چک کنم

**Comment by alirezax5** [comment]
> سلام عزیز وقتت بخیر ممنون بابت پروژه ی خوبت من از addnewClient استفاده میکنم یوزر ساخته میشه ولی تو پنل ارور میده از نمونه کد های خودتونم استفاده کردم همینطور بود ورژن پنلی که تست کردم ثنایی 2.0.2 و 1.7.9 بوده راهنمایی میفرمایید

و یک عکس از خطاش بدین

**Comment by MortezaRajabzadeh** [comment]
$xui->addnewClient(8, '793616d8-4f2f-7ea1-aa1a-0ea49159765f', "tesade2", '',  '', '',  50,  Carbon::now()->addDays(30),  0,  'chrome',  false)
این کد میزنم حجم اضافه نمیکنه

**Comment by alirezax5** [comment]
> $xui->addnewClient(8, '793616d8-4f2f-7ea1-aa1a-0ea49159765f', "tesade2", '', '', '', 50, Carbon::now()->addDays(30), 0, 'chrome', false) این کد میزنم حجم اضافه نمیکنه

حجم باید تبدیل به بایت بشه ، الان ۵۰ بایت گذاشتید.

**Comment by MortezaRajabzadeh** [comment]
ممنون ااون مشکل حل شد بخوام کانفیگو برای کاربر ارسال کنم چطور تبدیل کنم
