### ISSUE TITLE
فانکشن delClient کار نمیکنه

### ISSUE THREAD

**Issue by asadace1** [alirezax5/xuiapi#32]
سلام وقت بخیر
فانکشن delClient مقدار نول برمیگردونه چه با uuid چه با email
پنل علیرضا تست کردم فقط

**Comment by alirezax5** [comment]
__

> سلام وقت بخیر فانکشن delClient مقدار نول برمیگردونه چه با uuid چه با email پنل علیرضا تست کردم فقط

سلام نسخه های قبل هم مشکل داشته؟

**Comment by asadace1** [comment]
> __
> 
> > سلام وقت بخیر فانکشن delClient مقدار نول برمیگردونه چه با uuid چه با email پنل علیرضا تست کردم فقط
> 
> سلام نسخه های قبل هم مشکل داشته؟

آره از همون اول delClient  کار نمیکرد و من از متد editInbound برای حذف یک کلاینت استفاده میکنم

**Comment by asadace1** [comment]
حل شد مشکل از مسیر پست بود
 'delClient' => '/xui/inbound/delClient/{id}',
این مسیر تو پنل علیرضا درست نیست
و با تغییرش به مسیر زیر حل شد:
'delClient' => '/xui/inbound/{id}/delClient/{client}',

**Comment by alirezax5** [comment]
> /xui/inbound/{id}/delClient/{client}

ممنون
