### ISSUE TITLE
for 3x-ui

### ISSUE THREAD

**Issue by Asseken** [alirezax5/xuiapi#34]
Hello, I would like to use it for 3X-UI. How should I run it locally. Is it necessary to modify the URL and account password in the example?

**Comment by alirezax5** [comment]
Hello, you need to enter your xui panel information in the source.

The login example is mentioned in the examples.

The script has not been updated for a long time, if you encounter a problem, let me know and I will check it

**Comment by Asseken** [comment]
> 你好，你需要在源中输入你的xui面板信息。
> 
> 示例中提到了登录示例。
> 
> 脚本已经很久没有更新了，如果遇到问题，告诉我，我会检查

Okay, thank you.
