### ISSUE TITLE
دریافت وضعیت آنلاین بودن کلاینت توسط api

### ISSUE THREAD

**Issue by alivezvar** [alirezax5/xuiapi#35]
سلام
میتونید به api بخشی رو اضافه کنید که وضعیت آنلاین بودن کلاینت هم بتونیم دریافت کنیم؟

**Comment by alirezax5** [comment]
سلام تا آخر هفته xui هارو نگاه میکنم اگه بشه که به سورس اضافه میکنم

**Comment by alivezvar** [comment]
سپاس 👌

**Comment by alirezax5** [comment]
> سلام میتونید به api بخشی رو اضافه کنید که وضعیت آنلاین بودن کلاینت هم بتونیم دریافت کنیم؟

نگاه کردم هم سنایی هم علیرضا متد showOnlines رو براشون نوشتم که میتونید با in_array بررسی کنید که کلاینت داخل آرایه هستش یا خیر.

**Comment by OghabTeam** [comment]
داداش showOnlines داخل سورس ثنایی نزاشتی دستی هم گذاشتم null نشون میده فک کنم ثنایی نداره!؟

**Comment by OghabTeam** [comment]
> > سلام میتونید به api بخشی رو اضافه کنید که وضعیت آنلاین بودن کلاینت هم بتونیم دریافت کنیم؟
> 
> نگاه کردم هم سنایی هم علیرضا متد showOnlines رو براشون نوشتم که میتونید با in_array بررسی کنید که کلاینت داخل آرایه هستش یا خیر.

میشه اینو اوکی کنی

**Comment by alirezax5** [comment]
> داداش showOnlines داخل سورس ثنایی نزاشتی دستی هم گذاشتم null نشون میده فک کنم ثنایی نداره!؟

احتمالا یادم رفته بزارم تا اخر هفته تغییراتشون رو نگاه میکنم و براساشون آپدیت میکنم
