### ISSUE TITLE
connection issues for custom ports

### ISSUE THREAD

**Issue by mostafa9112** [alirezax5/xuiapi#4]
Hello, I apologize for so many questions
When unusual ports are used for the panel, the code cannot connect to the panel and only connects to public ports, such as: 80.443.2083
Firewall off
Firewall turned on and ports added
But it still doesn't work
And I need this item to prevent the panel address from leaking and hacking it

**Comment by alirezax5** [comment]
> Hello, I apologize for so many questions When unusual ports are used for the panel, the code cannot connect to the panel and only connects to public ports, such as: 80.443.2083 Firewall off Firewall turned on and ports added But it still doesn't work And I need this item to prevent the panel address from leaking and hacking it

For more security, fill in the path field and change the ssh port

If you use the Cloudflare proxy, only https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/ ports are open.

**Comment by mostafa9112** [comment]
> > Hello, I apologize for so many questions When unusual ports are used for the panel, the code cannot connect to the panel and only connects to public ports, such as: 80.443.2083 Firewall off Firewall turned on and ports added But it still doesn't work And I need this item to prevent the panel address from leaking and hacking it
> 
> For more security, fill in the path field and change the ssh port
> 
> If you use the Cloudflare proxy, only https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/ ports are open.

i using server ip and connect to server directly but still not connected with many ports:
Failed to connect to 99.172.92.37 port 23232 after 1040 ms: Connection refused

**Comment by alirezax5** [comment]
> > > Hello, I apologize for so many questions When unusual ports are used for the panel, the code cannot connect to the panel and only connects to public ports, such as: 80.443.2083 Firewall off Firewall turned on and ports added But it still doesn't work And I need this item to prevent the panel address from leaking and hacking it
> > 
> > 
> > For more security, fill in the path field and change the ssh port
> > If you use the Cloudflare proxy, only https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/ ports are open.
> 
> i using server ip and connect to server directly but still not connected with many ports: Failed to connect to 99.172.92.37 port 23232 after 1040 ms: Connection refused

Do you mean the connection between my source and the panel? You must open the cpanel or directadmin port to establish a connection

**Comment by mostafa9112** [comment]
but x-ui installed directly on ubuntu and ports are open

**Comment by alirezax5** [comment]
> but x-ui installed directly on ubuntu and ports are open

I don't mean the x-ui server, I mean the server or host where you installed xuiapi
