### ISSUE TITLE
what is Cookie.txt

### ISSUE THREAD

**Issue by sajjadnasiribrn** [alirezax5/xuiapi#5]
سلام. یه فایل به نام Cookie.txt وجود داره توی کد ها، این محتویاتش چی باید باشه؟ از کجا باید این کوکی رو بیاریم؟

**Comment by alirezax5** [comment]
> سلام. یه فایل به نام Cookie.txt وجود داره توی کد ها، این محتویاتش چی باید باشه؟ از کجا باید این کوکی رو بیاریم؟

سلام ، برای ذخیره اطلاعات ورود استفاده میشه و خودکار ساخته میشه

مثل مثال مسیر فایل کوکی رو کنار ایندکس بسازید تا توی پوشه xuiapi نسازتش.
https://github.com/alirezax5/xuiapi#use

**Comment by sajjadnasiribrn** [comment]
آهان. ممنون. توی کدها تو سازنده کلاس base نوشتید آدرس cookie.txt رو بگیره و بریزه توی اتریبیوت. با c کوچیک. ولی جاهای دیگه Cookie.txt نوشتید. با c بزرگ. این دلیلش چیه؟

**Comment by alirezax5** [comment]
> آهان. ممنون. توی کدها تو سازنده کلاس base نوشتید آدرس cookie.txt رو بگیره و بریزه توی اتریبیوت. با c کوچیک. ولی جاهای دیگه Cookie.txt نوشتید. با c بزرگ. این دلیلش چیه؟

چیزی که توی سازندس کنار بیس میسازه ، توی نمونه کدا کنار فایلی که اجرا میشه.

اسامی فایل هم مهم نیست چی باشه ، اگه با فانکشن مسیر جدید بزاری همون مسیرش میشه

**Comment by sajjadnasiribrn** [comment]
دست شما درد نکنه. من هر api رو کال میکنم، بهم 404 برمیگردونه. اگه تجربشو داشتید لطفا راهنمایی کنید.

**Comment by alirezax5** [comment]
> دست شما درد نکنه. من هر api رو کال میکنم، بهم 404 برمیگردونه. اگه تجربشو داشتید لطفا راهنمایی کنید.

با استفاده از سورسم؟

**Comment by sajjadnasiribrn** [comment]
هم با استفاده از سوروس و هم معمولی. url دقیقا همینه که باید باشه.

**Comment by alirezax5** [comment]
> هم با استفاده از سوروس و هم معمولی. url دقیقا همینه که باید باشه.

ادرس پنل رو دذست وارد میکنی؟ path هم باید داخلش باشه

**Comment by sajjadnasiribrn** [comment]
path چیه؟
آدرس رو به صورت 
http://ip:port/xui/inbound/list
 وارد کردم.

**Comment by sajjadnasiribrn** [comment]
و توی cookie.txt هم متن زیر رو فقط نوشته:
# Netscape HTTP Cookie File
# https://curl.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

**Comment by sajjadnasiribrn** [comment]
متوجه شدم مشکل چی بود. کاربر داکر چون root نبود، اجازه ساخت فایل cookie.txt در صورت نبودنش رو نداشت و همین مشکل ایجاد میکرد. من تونستم وصل شم. با تشکر از شما.

**Comment by alirezax5** [comment]
> متوجه شدم مشکل چی بود. کاربر داکر چون root نبود، اجازه ساخت فایل cookie.txt در صورت نبودنش رو نداشت و همین مشکل ایجاد میکرد. من تونستم وصل شم. با تشکر از شما.

خواهش
موفق باشی
