### ISSUE TITLE
add MHsanaei and alireza0 panels

### ISSUE THREAD

**Issue by mostafa9112** [alirezax5/xuiapi#6]
hi alireza
plz add MHsanaei and alireza0 panels
thankyou

**Comment by alirezax5** [comment]
Hello

I think they are compatible with the HexaSoftwareTech class

**Comment by alirezax5** [comment]
> tnx. how detect panel owner with php via connect to panel?

Do you want to receive admin login information?

**Comment by mostafa9112** [comment]
> > tnx. how detect panel owner with php via connect to panel?
> 
> Do you want to receive admin login information?

I did not catch you

**Comment by alirezax5** [comment]
> > > tnx. how detect panel owner with php via connect to panel?
> > 
> > 
> > Do you want to receive admin login information?
> 
> I did not catch you

😂😑نفهمیدم منظورت چیه فارسی بنویس خودمو خودتو راحت کن

**Comment by mostafa9112** [comment]
راحتم کردی 😂  میگم چجوی با php بفهمم پنل مال کیه؟ که از سورس شما استفاده کنم؟ میخوام اسکریپت خودکار تشخیص بده

**Comment by alirezax5** [comment]
> راحتم کردی 😂 میگم چجوی با php بفهمم پنل مال کیه؟ که از سورس شما استفاده کنم؟ میخوام اسکریپت خودکار تشخیص بده

که کی توسعش داده؟ اینکارو نمیشه کرد
