### ISSUE TITLE
it doesn't work on the server

### ISSUE THREAD

**Issue by immortal25ir** [alirezax5/xuiapi#7]
hi, 
Everything is ok on localhost, but it doesn't work on server
In a similar issue, the firewall was mentioned. Such a tool is not available in shared hosting.
Isn't there a better solution?

**Comment by alirezax5** [comment]
> hi, Everything is ok on localhost, but it doesn't work on server In a similar issue, the firewall was mentioned. Such a tool is not available in shared hosting. Isn't there a better solution?

سلام ، از هاستینگ بخواید پورتو باز کنه یا ی پورت معمول رو بزارید برای پنل مثل 2083 , 2053,443, 2082 و..

**Comment by immortal25ir** [comment]
سلام
هم پورت رو باز کردن، هم آی پی‌رو توی لیست سفید گذاشتن. اما فایده ای نداشت
این آی پی‌هایی که اشاره کردین هم مربوط به کلودفلره و واسم در رابطه با CURL روی IP جواب نداد

**Comment by alirezax5** [comment]
> سلام هم پورت رو باز کردن، هم آی پی‌رو توی لیست سفید گذاشتن. اما فایده ای نداشت این آی پی‌هایی که اشاره کردین هم مربوط به کلودفلره و واسم در رابطه با CURL روی IP جواب نداد

سلام این پورتا معمولا توی اکثرا سرویس دهنده ها بازن
و داخل قسمت پنل path هم وارد میکنید؟ 
خطایی خاصی نمایش نمیده؟

**Comment by immortal25ir** [comment]
> > سلام هم پورت رو باز کردن، هم آی پی‌رو توی لیست سفید گذاشتن. اما فایده ای نداشت این آی پی‌هایی که اشاره کردین هم مربوط به کلودفلره و واسم در رابطه با CURL روی IP جواب نداد
> 
> سلام این پورتا معمولا توی اکثرا سرویس دهنده ها بازن و داخل قسمت پنل path هم وارد میکنید؟ خطایی خاصی نمایش نمیده؟

2. نه، path وارد نکردم
3. نه، فقط برگشتی null هست. اگرچه توی Localhost اوکی هست همه‌چیز

**Comment by alirezax5** [comment]
> > > سلام هم پورت رو باز کردن، هم آی پی‌رو توی لیست سفید گذاشتن. اما فایده ای نداشت این آی پی‌هایی که اشاره کردین هم مربوط به کلودفلره و واسم در رابطه با CURL روی IP جواب نداد
> > 
> > 
> > سلام این پورتا معمولا توی اکثرا سرویس دهنده ها بازن و داخل قسمت پنل path هم وارد میکنید؟ خطایی خاصی نمایش نمیده؟
> 
> 2. نه، path وارد نکردم
> 3. نه، فقط برگشتی null هست. اگرچه توی Localhost اوکی هست همه‌چیز

ورودی login رو true بزار ببین اوک میشه؟ اگ نشد از تلگرام اطلاعات سی پنلتونو بدید نگاه کنم
و اطلاعات تلگرام داخل پروفایل گیتهابم هس

**Comment by immortal25ir** [comment]
> > > > سلام هم پورت رو باز کردن، هم آی پی‌رو توی لیست سفید گذاشتن. اما فایده ای نداشت این آی پی‌هایی که اشاره کردین هم مربوط به کلودفلره و واسم در رابطه با CURL روی IP جواب نداد
> > > 
> > > 
> > > سلام این پورتا معمولا توی اکثرا سرویس دهنده ها بازن و داخل قسمت پنل path هم وارد میکنید؟ خطایی خاصی نمایش نمیده؟
> > 
> > 
> > 
> > 2. نه، path وارد نکردم
> > 3. نه، فقط برگشتی null هست. اگرچه توی Localhost اوکی هست همه‌چیز
> 
> ورودی login رو true بزار ببین اوک میشه؟ اگ نشد از تلگرام اطلاعات سی پنلتونو بدید نگاه کنم و اطلاعات تلگرام داخل پروفایل گیتهابم هس

حل شد، تشکر.

**Comment by alirezax5** [comment]
> > > > > سلام هم پورت رو باز کردن، هم آی پی‌رو توی لیست سفید گذاشتن. اما فایده ای نداشت این آی پی‌هایی که اشاره کردین هم مربوط به کلودفلره و واسم در رابطه با CURL روی IP جواب نداد
> > > > 
> > > > 
> > > > سلام این پورتا معمولا توی اکثرا سرویس دهنده ها بازن و داخل قسمت پنل path هم وارد میکنید؟ خطایی خاصی نمایش نمیده؟
> > > 
> > > 
> > > 
> > > 2. نه، path وارد نکردم
> > > 3. نه، فقط برگشتی null هست. اگرچه توی Localhost اوکی هست همه‌چیز
> > 
> > 
> > ورودی login رو true بزار ببین اوک میشه؟ اگ نشد از تلگرام اطلاعات سی پنلتونو بدید نگاه کنم و اطلاعات تلگرام داخل پروفایل گیتهابم هس
> 
> حل شد، تشکر.

چون قبلا فایل کوکی ساخته شده و مشکل ارتباط داشته، اطلاعات لاگین ذخیره نشده بوده ، برای اینکه مدام لاگین نکنه گذاشتم ی بار کوکی بسازه ، true که گذاشتی دیگه فورس شدش

موفق باشی

**Comment by immortal25ir** [comment]
> > > > > > سلام هم پورت رو باز کردن، هم آی پی‌رو توی لیست سفید گذاشتن. اما فایده ای نداشت این آی پی‌هایی که اشاره کردین هم مربوط به کلودفلره و واسم در رابطه با CURL روی IP جواب نداد
> > > > > 
> > > > > 
> > > > > سلام این پورتا معمولا توی اکثرا سرویس دهنده ها بازن و داخل قسمت پنل path هم وارد میکنید؟ خطایی خاصی نمایش نمیده؟
> > > > 
> > > > 
> > > > 
> > > > 2. نه، path وارد نکردم
> > > > 3. نه، فقط برگشتی null هست. اگرچه توی Localhost اوکی هست همه‌چیز
> > > 
> > > 
> > > ورودی login رو true بزار ببین اوک میشه؟ اگ نشد از تلگرام اطلاعات سی پنلتونو بدید نگاه کنم و اطلاعات تلگرام داخل پروفایل گیتهابم هس
> > 
> > 
> > حل شد، تشکر.
> 
> چون قبلا فایل کوکی ساخته شده و مشکل ارتباط داشته، اطلاعات لاگین ذخیره نشده بوده ، برای اینکه مدام لاگین نکنه گذاشتم ی بار کوکی بسازه ، true که گذاشتی دیگه فورس شدش
> 
> موفق باشی

ممنون ازت
