### ISSUE TITLE
عدم سازگاری با پنل های جدید

### ISSUE THREAD

**Issue by asadace1** [alirezax5/xuiapi#8]
سلام کار عالیه فقط اینکه با پنلهای جدید سارگاز نیست و الان کسی دیگه از پنلهای قدیمی استفاده نمیکنه
الان همه از پنلهای مولتی یوزر با یک پورت استفاده میکنن
شما نوشتین با پنل NidukaAkalanka هم کار میکنه در حالیکه این پنل مولتی یورز هست و این وب سرویس برای این نوع پنل ها نیس
شما تو فانکشنهای NidukaAkalanka نوشیتن addInbound این پنل اینجوری کار نمیکنه
بازم ممنون از شما

**Comment by alirezax5** [comment]
سلام اکثر پنل هایی که ایرانی ها استفاده میکنن  از HexaSoftwareTech یا اسدی سابق فورک شدن که اطلاعات کلایمت ها داخل ارایه settings ارسال میشه

**Comment by alirezax5** [comment]
حالا اگه جدیدا تغییراتی داده باشن که با سورس مچ باشه توی بروزرسانی بعدی میزارم

**Comment by alirezax5** [comment]
> سلام کار عالیه فقط اینکه با پنلهای جدید سارگاز نیست و الان کسی دیگه از پنلهای قدیمی استفاده نمیکنه الان همه از پنلهای مولتی یوزر با یک پورت استفاده میکنن شما نوشتین با پنل NidukaAkalanka هم کار میکنه در حالیکه این پنل مولتی یورز هست و این وب سرویس برای این نوع پنل ها نیس شما تو فانکشنهای NidukaAkalanka نوشیتن addInbound این پنل اینجوری کار نمیکنه بازم ممنون از شما

فردا پس فردا پنل ثنایی و علیرضا اضافه میشه.
تغییرات خوبی دادن

**Comment by asadace1** [comment]
> سلام اکثر پنل هایی که ایرانی ها استفاده میکنن از HexaSoftwareTech یا اسدی سابق فورک شدن که اطلاعات کلایمت ها داخل ارایه settings ارسال میشه
دقیقا بعله ولی تو فانکشنهای HexaSoftwareTech که شما نوشته بودین نمیشه با کلاینتها کار کرد
مثلا نمیشه یه کلاینت رو  اضافه یا ادیت کرد باید اول json کلاینت به setting اضافه بشه بعد کل ستینگ رو به اینباند اضافه کنیم ک کار من نیست ادد کردن یا پیدا کردن کلاینت از اون json خفن تو setting
ممنون بازم

**Comment by asadace1** [comment]
> سلام اکثر پنل هایی که ایرانی ها استفاده میکنن از HexaSoftwareTech یا اسدی سابق فورک شدن که اطلاعات کلایمت ها داخل ارایه settings ارسال میشه

دقیقا بعله ولی تو فانکشنهای HexaSoftwareTech که شما نوشته بودین نمیشه با کلاینتها کار کرد
مثلا نمیشه یه کلاینت رو اضافه یا ادیت کرد باید اول json کلاینت به setting اضافه بشه بعد کل ستینگ رو به اینباند اضافه کنیم ک کار من نیست ادد کردن یا پیدا کردن کلاینت از اون json خفن تو setting
ممنون بازم

**Comment by asadace1** [comment]
> > سلام کار عالیه فقط اینکه با پنلهای جدید سارگاز نیست و الان کسی دیگه از پنلهای قدیمی استفاده نمیکنه الان همه از پنلهای مولتی یوزر با یک پورت استفاده میکنن شما نوشتین با پنل NidukaAkalanka هم کار میکنه در حالیکه این پنل مولتی یورز هست و این وب سرویس برای این نوع پنل ها نیس شما تو فانکشنهای NidukaAkalanka نوشیتن addInbound این پنل اینجوری کار نمیکنه بازم ممنون از شما
> 
> فردا پس فردا پنل ثنایی و علیرضا اضافه میشه. تغییرات خوبی دادن

مرسی

**Comment by alirezax5** [comment]
> > > سلام کار عالیه فقط اینکه با پنلهای جدید سارگاز نیست و الان کسی دیگه از پنلهای قدیمی استفاده نمیکنه الان همه از پنلهای مولتی یوزر با یک پورت استفاده میکنن شما نوشتین با پنل NidukaAkalanka هم کار میکنه در حالیکه این پنل مولتی یورز هست و این وب سرویس برای این نوع پنل ها نیس شما تو فانکشنهای NidukaAkalanka نوشیتن addInbound این پنل اینجوری کار نمیکنه بازم ممنون از شما
> > 
> > 
> > فردا پس فردا پنل ثنایی و علیرضا اضافه میشه. تغییرات خوبی دادن
> 
> مرسی

اضافه شد اما addClient اون چیزی نیست که فکرشو بکنیم این هم اول لیست رو میگیره و بعد باید اضافش کنیم.
اگه به توسعه دهندش دسترسی دارید پیشنهاد کنید api برای پنل آماده سازی کنه , این سورس فقط به مسیرهایی که ادم عادی دسترسی داره اطلاعات میفرسته.

**Comment by asadace1** [comment]
> اضافه شد اما addClient اون چیزی نیست که فکرشو بکنیم این هم اول لیست رو میگیره و بعد باید اضافش کنیم. اگه به توسعه دهندش دسترسی دارید پیشنهاد کنید api برای پنل آماده سازی کنه , این سورس فقط به مسیرهایی که ادم عادی دسترسی داره اطلاعات میفرسته.

درسته، بعله پیشنهاد رو میدم بهشون و اگر api برای پنلشون آماده کنن بهتون اطلاع میدم

**Comment by asadace1** [comment]
من یه سرچ کردم تو گیتهاب یه نفر یه کلاسی نوشته که addClient هم داره ولی من نتونستم تست کنم
https://github.com/mobinjavari/v2ray-api-php

**Comment by alirezax5** [comment]
> من یه سرچ کردم تو گیتهاب یه نفر یه کلاسی نوشته که addClient هم داره ولی من نتونستم تست کنم https://github.com/mobinjavari/v2ray-api-php

اومده لیست رو دریافت کرده و بهش اضافه میکنه
گذاشتنش کاری نداره

**Comment by asadace1** [comment]
درسته، برای شما راحته نه برای من مبتدی، به هرحال ممنونم فقط من یه مشکلی دارم
من با استفاده از سورس شما نمیتونم listInbound() رو بخونم
یعنی فقط ستینگ پنل و status() کار میکنه ولی listInbound() و هر فانکشنی که مسیر /xui/inbound رو داره فقط ارایه خالی {} رو برمیگردونه

**Comment by alirezax5** [comment]
> درسته، برای شما راحته نه برای من مبتدی، به هرحال ممنونم فقط من یه مشکلی دارم من با استفاده از سورس شما نمیتونم listInbound() رو بخونم یعنی فقط ستینگ پنل و status() کار میکنه ولی listInbound() و هر فانکشنی که مسیر /xui/inbound رو داره فقط ارایه خالی {} رو برمیگردونه

کدوم پنل

**Comment by asadace1** [comment]
> کدوم پنل

همه اشون. من از ثنایی استفاده میکنم ولی همه رو تست کردم بازم فرقی نکرد

**Comment by alirezax5** [comment]
> > کدوم پنل
> 
> همه اشون. من از ثنایی استفاده میکنم ولی همه رو تست کردم بازم فرقی نکرد

تستش کردم اوک بود

**Comment by asadace1** [comment]
مشکل چی میتونه باشه؟ هم با ssl هم بدون ssl تست کردم فرقی نکرد

**Comment by asadace1** [comment]
مشکل چی میتونه باشه؟ هم با ssl هم بدون ssl تست کردم فرقی نکرد، آخه استاتوس یا ستینگ کار میکنه ولی اینباندها نه

**Comment by alirezax5** [comment]
> مشکل چی میتونه باشه؟ هم با ssl هم بدون ssl تست کردم فرقی نکرد، آخه استاتوس یا ستینگ کار میکنه ولی اینباندها نه

نمیدونم سورسو دسکاری نکردی؟

**Comment by asadace1** [comment]
> > مشکل چی میتونه باشه؟ هم با ssl هم بدون ssl تست کردم فرقی نکرد، آخه استاتوس یا ستینگ کار میکنه ولی اینباندها نه
> 
> نمیدونم سورسو دسکاری نکردی؟

نه، ثتایی دو روز پیش آپدیت داده برای پنلش. منم آپدیت کردم پنل رو، شما روی آخرین آپدیتش تست کردین؟ ورژن v1.1.2

**Comment by alirezax5** [comment]
> > > مشکل چی میتونه باشه؟ هم با ssl هم بدون ssl تست کردم فرقی نکرد، آخه استاتوس یا ستینگ کار میکنه ولی اینباندها نه
> > 
> > 
> > نمیدونم سورسو دسکاری نکردی؟
> 
> نه، ثتایی دو روز پیش آپدیت داده برای پنلش. منم آپدیت کردم پنل رو، شما روی آخرین آپدیتش تست کردین؟ ورژن v1.1.2

اره

**Comment by asadace1** [comment]
اوکی شد تونستم اینباند و حتی ستینگ رو بگیرم. مممونم

**Comment by alighanbarii** [comment]
سلام و درود .اگر لطف کنید بگید برای پنل ثنایی متد addClient برای id , $setting$ دقیقا چجوری داده بفرستیم و با چه فرمتی؟json قسمت ستینگ باید چه چیز هایی رو توش بنویسم؟

**Comment by alirezax5** [comment]
سلام اطلاعات کلاینت ها
مثل :

```php
$settings = [
    'clients' => [
        [
            'id' => '4',
            'email' => '4',
            'alterId' => '0',
        ]
    ],
    'disableInsecureEncryption' => false
];
```

و id هم ایدی ورودی یا همون inbound
دقت کنید مثل قبل باید تمام اطلاعات کلاینت هارو دریافت کنید بعد کلاینت جدید رو اضافه کنید.
بزودی یکم بهترش میکنم که کار با کلاینت ها یکم ساده بشه

**Comment by alighanbarii** [comment]
یعنی با listInbounds بیام از inbound قسمت ستینگ رو بردارم و و به لیست clients یدونه ارایه دیگه اضافه کنم بعد کل settings اولیه مربوط به inbound رو بدم به این متد؟
اره ممنون میشم واقعا سورس خفنی شده

**Comment by alirezax5** [comment]
> یعنی با listInbounds بیام از inbound قسمت ستینگ رو بردارم و و به لیست clients یدونه ارایه دیگه اضافه کنم بعد کل settings اولیه مربوط به inbound رو بدم به این متد؟ اره ممنون میشم واقعا سورس خفنی شده

اره
اقای ثنایی میتونستند سکت بک اند گار اضافه کردن کلاینت انجام بدن حالا اینجوری نوشتنش

**Comment by alighanbarii** [comment]
واقعا ممنون بابت پاسخگوییتون
هیچکدوم از پنل ها api مستقیم برا addclient داره؟
لینک اتصال vless رو هم بر اساس vless://guid@host.... بدم بعدش؟ یا خود پنل api داره که لینک رو برگردونه؟

**Comment by alirezax5** [comment]
> واقعا ممنون بابت پاسخگوییتون هیچکدوم از پنل ها api مستقیم برا addclient داره؟ لینک اتصال vless رو هم بر اساس vless://guid@host.... بدم بعدش؟ یا خود پنل api داره که لینک رو برگردونه؟

نه خوذ پنل برنمیگردونه

**Comment by alighanbarii** [comment]
الان اسکریپت رو نوشتم و از کامپیوتر خودم به راحتی وصل میشه و کلاینت اضاف میکنه ولی همین اسکریپت رو گذاشتم توی همون سرور پنل که با ربات کار کنه لاگین نمیشه.حتی url رو هم کردم localhost:panelPort ولی جواب نمیده

**Comment by asadace1** [comment]
$xui = base('https://'.ip.':port', 'user', 'pass');
	$xui->setCookie(__DIR__ .'/cookies/cookie.txt');
	$xui->login($force = true);
	$inboundList = $xui->listInbound();
	$inboundId = $inboundList["obj"][0]["id"]; // 0 is inbound 1 and 1 is inbound2
	$settingsList = json_decode($inboundList["obj"][0]["settings"], true); // 0 is inbound 1 and 1 is inbound2

	//add clients to selected inbound
	$data =json_decode('{
       "id": "4d70b5d8-f980-4fc4-b8e3-4b4919040064",
       "alterId": 0,
       "email": "test",
       "limitIp": 0,
       "totalGB": 2147483648,
       "expiryTime": 1673788732494
        }', true);
	$data['id'] = $id;
	$data['email'] = $email;
	$data['totalGB'] = $totalGB;
	$data['expiryTime'] = $expiryTime;
	array_push($settingsList['clients'], $data);
	$xui->addClient($inboundId, $settingsList);

**Comment by asadace1** [comment]
> یعنی با listInbounds بیام از inbound قسمت ستینگ رو بردارم و و به لیست clients یدونه ارایه دیگه اضافه کنم بعد کل settings اولیه مربوط به inbound رو بدم به این متد؟ اره ممنون میشم واقعا سورس خفنی شده

$xui = base('https://'ip':'port', 'user', 'pass');
$xui->setCookie(__DIR__ .'/cookies/cookie.txt');
$xui->login($force = true);
$inboundList = $xui->listInbound();
$inboundId = $inboundList["obj"][0]["id"]; // 0 is inbound 1 and 1 is inbound2
$settingsList = json_decode($inboundList["obj"][0]["settings"], true); // 0 is inbound 1 and 1 is inbound2

//add clients to selected inbound
$data =json_decode('{
   "id": "4d70b5d8-f980-4fc4-b8e3-4b4919040064",
   "alterId": 0,
   "email": "test",
   "limitIp": 0,
   "totalGB": 2147483648,
   "expiryTime": 1673788732494
    }', true);
$data['id'] = $id;
$data['email'] = $email;
$data['totalGB'] = $totalGB;
$data['expiryTime'] = $expiryTime;
array_push($settingsList['clients'], $data);
$xui->addClient($inboundId, $settingsList);

**Comment by asadace1** [comment]
منتها برای تمدید کلاینت جواب نمیده و اون داستان داره

**Comment by alirezax5** [comment]
> الان اسکریپت رو نوشتم و از کامپیوتر خودم به راحتی وصل میشه و کلاینت اضاف میکنه ولی همین اسکریپت رو گذاشتم توی همون سرور پنل که با ربات کار کنه لاگین نمیشه.حتی url رو هم کردم localhost:panelPort ولی جواب نمیده

 اگه روی سرور رانش کردی با فایل کوکی رو دسترسی بهش بدی

**Comment by alirezax5** [comment]
> منتها برای تمدید کلاینت جواب نمیده و اون داستان داره

حجم هارو توی کلاینت وارد میکنین بروز نمیشه؟

**Comment by asadace1** [comment]
> حجم هارو توی کلاینت وارد میکنین بروز نمیشه؟

کار نمیکنه update client
دستی هم کلاینت هارو میگیرم و حجم جدید و تایم جدید میدم و با ستینگ و اینباند میفرستم که اینجوری هم کلاینت فقط تو ستینگ بروز میشه تو client list که همون clinet status هست بروز نمیشه
و درواقع ترافیک مصرفی نمیندازه دیگه

**Comment by alirezax5** [comment]
> > حجم هارو توی کلاینت وارد میکنین بروز نمیشه؟
> 
> کار نمیکنه update client دستی هم کلاینت هارو میگیرم و حجم جدید و تایم جدید میدم و با ستینگ و اینباند میفرستم که اینجوری هم کلاینت فقط تو ستینگ بروز میشه تو client list که همون clinet status هست بروز نمیشه و درواقع ترافیک مصرفی نمیندازه دیگه

توی سورسی که گذاشتم باید اندیس کلاینته رو به عنوان کلاینت پاس بدی

در کل json شامل ایناس :

id=1&settings={
  "clients": [
    {
      "id": "f9ce5973-ac37-420d-f98c-c5644a9518b9",
      "flow": "",
      "email": "i2gqckp",
      "limitIp": 0,
      "totalGB": 0,
      "expiryTime": ""
    },
    {
      "id": "1e12e6ce-3b5c-49d3-8a26-8ca04bd85fef",
      "flow": "",
      "email": "1vu3s5y",
      "limitIp": 0,
      "totalGB": 0,
      "expiryTime": ""
    }
  ],
  "decryption": "none",
  "fallbacks": []
}


وقت کنم فانکشن جدا مینویسم تا حدی ساده تر شه

**Comment by asadace1** [comment]
> 
درسته آره روش کار میکنم
مرسی ازت. منتظر آپدیت جدید هستیم

**Comment by alighanbarii** [comment]
> > الان اسکریپت رو نوشتم و از کامپیوتر خودم به راحتی وصل میشه و کلاینت اضاف میکنه ولی همین اسکریپت رو گذاشتم توی همون سرور پنل که با ربات کار کنه لاگین نمیشه.حتی url رو هم کردم localhost:panelPort ولی جواب نمیده
> 
> اگه روی سرور رانش کردی با فایل کوکی رو دسترسی بهش بدی

متوجه نمیشم. یعنی فایل کوکی رو با chmod دسترسیش رو تغییر بدم؟

**Comment by alirezax5** [comment]
> > > الان اسکریپت رو نوشتم و از کامپیوتر خودم به راحتی وصل میشه و کلاینت اضاف میکنه ولی همین اسکریپت رو گذاشتم توی همون سرور پنل که با ربات کار کنه لاگین نمیشه.حتی url رو هم کردم localhost:panelPort ولی جواب نمیده
> > 
> > 
> > اگه روی سرور رانش کردی با فایل کوکی رو دسترسی بهش بدی
> 
> متوجه نمیشم. یعنی فایل کوکی رو با chmod دسترسیش رو تغییر بدم؟

اره

**Comment by asadace1** [comment]
البته اینم بگم کلا پنل ثتایی خوب نیست و همه سورسها باهاش مشکل دارن
https://github.com/MrCenTury/xXx-UI
 این پنل هیچ مشکلی نداره در حالی که پنل ثتایی یکی در میون باگ میخوره

**Comment by alighanbarii** [comment]
الان متد های که نوشتین مثل addClient من بر اساس همون اسکریپت نوشتم روی این پنل هم کار میکنه؟

**Comment by alirezax5** [comment]
> الان متد های که نوشتین مثل addClient من بر اساس همون اسکریپت نوشتم روی این پنل هم کار میکنه؟

 mecen?
نمیدونم جدیده و تاحالا تست نکردم.

**Comment by asadace1** [comment]
> الان متد های که نوشتین مثل addClient من بر اساس همون اسکریپت نوشتم روی این پنل هم کار میکنه؟

آره من تست کردم مال ثنایی باگ داره این نداره

**Comment by alighanbarii** [comment]
> > الان متد های که نوشتین مثل addClient من بر اساس همون اسکریپت نوشتم روی این پنل هم کار میکنه؟
> 
> آره من تست کردم مال ثنایی باگ داره این نداره

شما که تست کردی با این سورس میشه بهش متصل شد؟اگه اره ممنون میشم اسکریپت رو ببینم

**Comment by asadace1** [comment]
> شما که تست کردی با این سورس میشه بهش متصل شد؟اگه اره ممنون میشم اسکریپت رو ببینم

ببین منظورت از اسکریپ نمیدونم چیه ولی اون کدهایی که بالا نوشتم جواب میده. خیلی ساده اس همونطور که استاد alirezax5 گفتن باید اینباند رو بگیری و ستینگ رو بگیری و بعد یه کلایت به صورت ارایه بهش اضافه کنی و بعد با ادد کلاینت بفرستی بره
همین الانم با پنل علیرضا تست کردم بهتر از همه پنل ها هستش . کاملا سازگاره

**Comment by alighanbarii** [comment]
تا الان همه چیز روی پنل ثنایی پیاده کردم جواب داده فقط این مسئله آپدیت کردن کانفیگ چی؟الان یه کانفیگ هم توی settings->clients وجود داره و هم  inbound['clientStats'] الان من بخوام زمانش رو اضافه کنم و up , down رو هم صفر کنم از همون clientStats برم ؟

**Comment by alirezax5** [comment]
@asadace1 @ali-khan-v21 
آپدیترو تست کنید

**Comment by alighanbarii** [comment]
متد آپدیت ؟کدوم متد؟آرگومان بهش چی بدم؟

**Comment by alirezax5** [comment]
> متد آپدیت ؟کدوم متد؟آرگومان بهش چی بدم؟

داخل ide اگه بنویسی ورودی هاشون میاد و از پوشه src میتونی نگاه کنی فانکشن هارو
و چندتا فانکشن برای حذف و اضافه کردن کلاینت اضافه کردم

**Comment by asadace1** [comment]
> 
سلام تست کردم عالیه کار راحت شده بسیار ممنوم

**Comment by asadace1** [comment]
> @asadace1 @ali-khan-v21 آپدیترو تست کنید

سلام تست کردم عالیه کار راحت شده بسیار ممنوم

**Comment by asadace1** [comment]
> تا الان همه چیز روی پنل ثنایی پیاده کردم جواب داده فقط این مسئله آپدیت کردن کانفیگ چی؟الان یه کانفیگ هم توی settings->clients وجود داره و هم inbound['clientStats'] الان من بخوام زمانش رو اضافه کنم و up , down رو هم صفر کنم از همون clientStats برم ؟

کلاینت استاتس اطلاعات کلاینت هارو نشون میده اون برای گرفتن اطلاعات اکانت هست
برای آپدیت کلاینت هم با استفاده از متد جدید،  تاریخ یا حجم کلاینت رو آپدیت کنید و بعد با ریست کلاینت همون کلاین رو ریست ترافیک کنید

**Comment by asadace1** [comment]
البته ریست ترافیک کلاینت کار نمیکنه مسیر curl درست نبود،درست کردم بازم ریست نمیشه کلاینت
{"success":true,"msg":"traffic reseted\u6210\u529f","obj":null}
خروجی اینه ولی انگار انجام نشده

**Comment by alirezax5** [comment]
> البته ریست ترافیک کلاینت کار نمیکنه مسیر curl درست نبود،درست کردم بازم ریست نمیشه کلاینت {"success":true,"msg":"traffic reseted\u6210\u529f","obj":null} خروجی اینه ولی انگار انجام نشده

ادرسشون اشتباس ، درستش میکنم

**Comment by asadace1** [comment]
> 
همین فقط ریست کلاینت مورد داره . بقیه فانکشن ها موری ندیدم . و ادیت بای ایمیل عالی بود. البته من خودم یه کدی نوشته بودم براش ولی این بهتره سریعتر و سیمپلتر

**Comment by asadace1** [comment]
میدونید مشکل اینه که دیتابیس پنل دوتا قسمت اصلی داره یکی اینباندها و یکی کلاینتها
حالا ما تو ادد یا ادیت اینباند مشکلی نداریم همه کد ها کار میکنه و به راحتی با ادد کلاینت میتونیم کلاینت جدید اضافه کنیم

مشکل تو آپدیت حجم یا expiryTime در یک کلاینت هست که چه با متد اصلی ادد کلایت و چه با متد اصلی ادیت اینباند انجام بدیم بخش کلاینت ها در دیتابیس چیزی اعمال نمیشه و تغییرات فقط تو ستینگ اینباد اعمال میشه برای همینه که بعد از انجام تو پنل بازم disable میزنه کلاینت رو

**Comment by alirezax5** [comment]
ریست حجم رو تست نکردم و فکر نکنم مشکلش اون باشه احتمالا اشتباه داده میفرستیم

و برای ویرایش زمان و ترافیک از متد جدیدا استفاده کن فقط ترافیکش برحسب گیگ بفرس

**Comment by alirezax5** [comment]
> میدونید مشکل اینه که دیتابیس پنل دوتا قسمت اصلی داره یکی اینباندها و یکی کلاینتها حالا ما تو ادد یا ادیت اینباند مشکلی نداریم همه کد ها کار میکنه و به راحتی با ادد کلاینت میتونیم کلاینت جدید اضافه کنیم
> 
> مشکل تو آپدیت حجم یا expiryTime در یک کلاینت هست که چه با متد اصلی ادد کلایت و چه با متد اصلی ادیت اینباند انجام بدیم بخش کلاینت ها در دیتابیس چیزی اعمال نمیشه و تغییرات فقط تو ستینگ اینباد اعمال میشه برای همینه که بعد از انجام تو پنل بازم disable میزنه کلاینت رو


ریست حجم رو تست نکردم و فکر نکنم مشکلش اون باشه احتمالا اشتباه داده میفرستیم

و برای ویرایش زمان و ترافیک از متد جدیدا استفاده کن فقط ترافیکش برحسب گیگ بفرس

**Comment by asadace1** [comment]
> ریست حجم رو تست نکردم و فکر نکنم مشکلش اون باشه احتمالا اشتباه داده میفرستیم
> 
> و برای ویرایش زمان و ترافیک از متد جدیدا استفاده کن فقط ترافیکش برحسب گیگ بفرس

انجام میدم و expiryTime و totalGB کلاینت تغییر میکنه اما بازم تو پنل disable میزنه اکانت رو
من اومدم دیتابیس رو کشیدم بیرون و باز کردم دیدم فقط کلاینت تو ستینگ تغییر پیدا کردن و توی جدول client traffic همون مقدار اولیه هست و تغییری ایجاد نشده برای همین هنوز disable میزنه تو پنل. شما هم همین مشکل رو داشتین؟؟

**Comment by asadace1** [comment]
آقا حل شد این موری که گفتم مربوط به کدها نبود از نسخه پنل بود اما هنوزم ریست کلاینت کار نمیکنه

**Comment by alirezax5** [comment]
> > ریست حجم رو تست نکردم و فکر نکنم مشکلش اون باشه احتمالا اشتباه داده میفرستیم
> > و برای ویرایش زمان و ترافیک از متد جدیدا استفاده کن فقط ترافیکش برحسب گیگ بفرس
> 
> انجام میدم و expiryTime و totalGB کلاینت تغییر میکنه اما بازم تو پنل disable میزنه اکانت رو من اومدم دیتابیس رو کشیدم بیرون و باز کردم دیدم فقط کلاینت تو ستینگ تغییر پیدا کردن و توی جدول client traffic همون مقدار اولیه هست و تغییری ایجاد نشده برای همین هنوز disable میزنه تو پنل. شما هم همین مشکل رو داشتین؟؟

اگه میتونی دیتابیستو بفرس

**Comment by alighanbarii** [comment]
این مورد غیر فعال موندن کاربر بعد از اپدیت برای کدوم پنل و ورژن بود؟الان من ثنایی 1.8 هم همون مشکلو دارم.ریست ترافیک چی 
اوکی شد؟

**Comment by asadace1** [comment]
> اگه میتونی دیتابیستو بفرس

چجوری بفرستم از کجا؟؟

**Comment by asadace1** [comment]
> این مورد غیر فعال موندن کاربر بعد از اپدیت برای کدوم پنل و ورژن بود؟الان من ثنایی 1.8 هم همون مشکلو دارم.ریست ترافیک چی اوکی شد؟
والا ورژن 1.0.9 نصب کردم یه لحظه درست شد بعدش دوباره اینجوری شد. نه ریست کلاینت رو من هنوز نتونستم کاری بکنم

**Comment by asadace1** [comment]
> این مورد غیر فعال موندن کاربر بعد از اپدیت برای کدوم پنل و ورژن بود؟الان من ثنایی 1.8 هم همون مشکلو دارم.ریست ترافیک چی اوکی شد؟

 والا ورژن 1.0.9 نصب کردم یه لحظه درست شد بعدش دوباره اینجوری شد. نه ریست کلاینت رو من هنوز نتونستم کاری بکنم

**Comment by alirezax5** [comment]
> > اگه میتونی دیتابیستو بفرس
> 
> چجوری بفرستم از کجا؟؟

از اپلودسنترا استفاده کن یا تل بفرست

**Comment by asadace1** [comment]
> از اپلودسنترا استفاده کن یا تل بفرست

باشه . میگم این پنل rest api جدید گذاشته بتونید اینو اضافه کنید عالی میشه و پنلش که واقعا عالیه
https://github.com/alireza0/x-ui

**Comment by mostafa9112** [comment]
> > ریست حجم رو تست نکردم و فکر نکنم مشکلش اون باشه احتمالا اشتباه داده میفرستیم
> > و برای ویرایش زمان و ترافیک از متد جدیدا استفاده کن فقط ترافیکش برحسب گیگ بفرس
> 
> انجام میدم و expiryTime و totalGB کلاینت تغییر میکنه اما بازم تو پنل disable میزنه اکانت رو من اومدم دیتابیس رو کشیدم بیرون و باز کردم دیدم فقط کلاینت تو ستینگ تغییر پیدا کردن و توی جدول client traffic همون مقدار اولیه هست و تغییری ایجاد نشده برای همین هنوز disable میزنه تو پنل. شما هم همین مشکل رو داشتین؟؟

چون تو پنل های جدید مثل ثنایی 1.0 به بالا وقتی کلاینتی از طریق updateInbound ایجاد میشه فقط توی جدول inbounds  فیلد settings ساخته میشه و برخلاف نسخه های قدیم توی جدول client_traffics ساخته نمیشه که باعث میشه مواردی مانند مصرف و فعال بودن کاربر ذخیره نشه

علیرضا جان دستم به دامنت کاری کن برامون حیرون شدیم با اپدیت پنل ها

**Comment by alirezax5** [comment]
> > از اپلودسنترا استفاده کن یا تل بفرست
> 
> باشه . میگم این پنل rest api جدید گذاشته بتونید اینو اضافه کنید عالی میشه و پنلش که واقعا عالیه https://github.com/alireza0/x-ui

توضیحی نداده body ای که ارسال میکنیم چیا باشه

**Comment by alirezax5** [comment]
@mostafa9112 @asadace1 @ali-khan-v21 
مشکل ریست حل شد و با ایمیل کلاینت باید ریستش کنید

**Comment by asadace1** [comment]
> @mostafa9112 @asadace1 @ali-khan-v21 مشکل ریست حل شد و با ایمیل کلاینت باید ریستش کنید
 
 یعنی به جای ایندکس کلاینت ایمیلشو بزاریم؟

**Comment by alirezax5** [comment]
> > @mostafa9112 @asadace1 @ali-khan-v21 مشکل ریست حل شد و با ایمیل کلاینت باید ریستش کنید
> 
> یعنی به جای ایندکس کلاینت ایمیلشو بزاریم؟

اره

https://github.com/alirezax5/xuiapi/blob/main/Examples/resetClientTraffic.php

**Comment by asadace1** [comment]
> https://github.com/alirezax5/xuiapi/blob/main/Examples/resetClientTraffic.

Uncaught TypeError: buy::getClient(): Return value must be of type int, string returned

این ارور رو میده. نوشته نمتونی string بدی باید عدد بدی. با ایندکس هم تست کردم کار نمیکنه کلا
دستورم اینه:
 $xui->resetClientTraffic(1, 'asadace1');

**Comment by asadace1** [comment]
{"success":true,"msg":"traffic reseted\u6210\u529f","obj":null}



> > > @mostafa9112 @asadace1 @ali-khan-v21 مشکل ریست حل شد و با ایمیل کلاینت باید ریستش کنید
> > 
> > 
> > یعنی به جای ایندکس کلاینت ایمیلشو بزاریم؟
> 
> اره
> 
> https://github.com/alirezax5/xuiapi/blob/main/Examples/resetClientTraffic.php

{"success":true,"msg":"traffic reseted\u6210\u529f","obj":null}

اینو میده ولی تو پنل ریست نمیشه. احتمالا به خاطر نسخه های پنل هست

**Comment by alirezax5** [comment]
> {"success":true,"msg":"traffic reseted\u6210\u529f","obj":null}
> 
> > > > @mostafa9112 @asadace1 @ali-khan-v21 مشکل ریست حل شد و با ایمیل کلاینت باید ریستش کنید
> > > 
> > > 
> > > یعنی به جای ایندکس کلاینت ایمیلشو بزاریم؟
> > 
> > 
> > اره
> > https://github.com/alirezax5/xuiapi/blob/main/Examples/resetClientTraffic.php
> 
> {"success":true,"msg":"traffic reseted\u6210\u529f","obj":null}
> 
> اینو میده ولی تو پنل ریست نمیشه. احتمالا به خاطر نسخه های پنل هست
composer update
بزن تا سورس اپدیت بشه

**Comment by alirezax5** [comment]
> {"success":true,"msg":"traffic reseted\u6210\u529f","obj":null}
> 
> > > > @mostafa9112 @asadace1 @ali-khan-v21 مشکل ریست حل شد و با ایمیل کلاینت باید ریستش کنید
> > > 
> > > 
> > > یعنی به جای ایندکس کلاینت ایمیلشو بزاریم؟
> > 
> > 
> > اره
> > https://github.com/alirezax5/xuiapi/blob/main/Examples/resetClientTraffic.php
> 
> {"success":true,"msg":"traffic reseted\u6210\u529f","obj":null}
> 
> اینو میده ولی تو پنل ریست نمیشه. احتمالا به خاطر نسخه های پنل هست

composer update
بزن تا سورس اپدیت بشه
